Repository forseti-security/forseti-security, pull requests merged in 2018-08, with the labels that each got.

#1841 Shorten the violation hash id to 32 characters for upload to CSCC
  google/cloud/forseti/notifier/notifiers/cscc_notifier.py
  tests/notifier/notifiers/cscc_notifier_test.py
Labels: cla: yes, status: in-progress

#1842 Update version to 2.1.0
  google/cloud/forseti/__init__.py
Labels: cla: yes, status: in-progress

#1852 Executing specific subset of tests
  _docs/_latest/develop/dev/testing.md
Labels: cla: yes, status: in-progress

#1851 Adding solution for error repeatedly encountered in forseti setup
  _docs/_latest/develop/dev/setup.md
Labels: cla: yes, status: in-progress

#1815 Fixes to gcloud.py and Service Account Support
  install/gcp/installer/forseti_installer.py
  install/gcp/installer/util/gcloud.py
Labels: cla: yes, status: in-progress

#1854 Refactor server.py to move config classes into base/config.py.
  google/cloud/forseti/services/base/__init__.py
  google/cloud/forseti/services/base/config.py
  google/cloud/forseti/services/server.py
  tests/scanner/scanner_test.py
  tests/services/api_tests/inventory_test.py
  tests/services/inventory/crawling_test.py
  tests/services/model/importer/update_test_dbs.py
  tests/services/server_test.py
  tests/services/util/mock.py
Labels: cla: yes, status: in-progress

#1858 Clean up test dependencies
  tests/common/gcp_api/cloud_resource_manager_test.py
  tests/common/gcp_api/cloudsql_test.py
  tests/common/gcp_api/test_data/fake_cloudsql_responses.py
  tests/common/gcp_api/test_data/fake_crm_responses.py
  tests/common/gcp_type/test_data/fake_folders.py
  tests/common/gcp_type/test_data/fake_orgs.py
  tests/common/gcp_type/test_data/fake_projects.py
  tests/notifier/notifiers/cscc_notifier_test.py
  tests/scanner/audit/instance_network_interface_engine_test.py
  tests/scanner/scanner_test.py
  tests/services/scanner/scanner_base_db.py
  tests/services/scanner/scanner_dao_test.py
  tests/services/util/gcp_env.py
  tests/services/util/protect.py
Labels: cla: yes, status: in-progress

#1857 [Issue 1848] Fix a test that is emitting errors and polluting the logs.
  tests/scanner/scanner_test.py
Labels: cla: yes, status: in-progress

#1863 Add FAQ for adding documentation
  _faq/general/create-issue.md
  _faq/general/updating-documentation.md
Labels: cla: yes, status: in-progress

#1867 Fixing copy and paste error in test description
  tests/notifier/notifier_test.py
Labels: cla: yes, status: in-progress

#1870 Added requriemodel decorator to the scanner run method, pin the version of rumael.yaml library
  google/cloud/forseti/services/client.py
  setup.py
Labels: cla: yes, status: in-progress

#1839 Add Billing Account log sinks to Inventory
  google/cloud/forseti/common/gcp_api/cloudbilling.py
  google/cloud/forseti/services/inventory/base/gcp.py
  google/cloud/forseti/services/inventory/base/resources.py
  google/cloud/forseti/services/model/importer/importer.py
  tests/common/gcp_api/cloudbilling_test.py
  tests/common/gcp_api/test_data/fake_cloudbilling_responses.py
  tests/services/inventory/crawling_test.py
  tests/services/inventory/gcp_api_mocks.py
  tests/services/inventory/test_data/mock_gcp_results.py
  tests/services/model/importer/test_data/forseti-test.db
Labels: cla: yes, status: in-progress

#1872 Add to Compute client the insert, update and delete firewall rules.
  google/cloud/forseti/common/gcp_api/_base_repository.py
  google/cloud/forseti/common/gcp_api/compute.py
  google/cloud/forseti/common/gcp_api/errors.py
  google/cloud/forseti/common/gcp_api/repository_mixins.py
  google/cloud/forseti/common/util/date_time.py
  tests/common/gcp_api/compute_test.py
  tests/common/gcp_api/test_data/fake_compute_responses.py
  tests/common/util/date_time_test.py
Labels: cla: yes, status: in-progress

#1873 Re-enable groups scanner test
  tests/scanner/groups_scanner_test.py
  tests/scanner/test_data/expected_root_with_rules.pickle
  tests/scanner/test_data/expected_root_without_rules.pickle
  tests/scanner/test_data/fake_groups_scanner_data.py
Labels: cla: yes, status: in-progress

#1877 Add the -r flag for requirements.txt
  _docs/v2.0/develop/dev/setup.md
Labels: cla: yes, status: in-progress

#1878 Fix iam scanner so that it audits allUsers correctly
  google/cloud/forseti/common/gcp_type/iam_policy.py
  tests/common/gcp_type/iam_policy_test.py
Labels: cla: yes, status: in-progress

#1876 Add the -r flag for requirements.txt
  _docs/v2.1/develop/dev/setup.md
Labels: cla: yes, status: in-progress

#1883 Collapse apt layers in base dockerfile
  install/docker/base
Labels: cla: yes, status: in-progress

#1874 Restore VPC Support
  deployment-templates/compute-engine/client/forseti-instance-client.py
  deployment-templates/compute-engine/client/forseti-instance-client.py.schema
  deployment-templates/compute-engine/server/forseti-instance-server.py
  deployment-templates/compute-engine/server/forseti-instance-server.py.schema
  deployment-templates/deploy-forseti-client.yaml.in
  deployment-templates/deploy-forseti-server.yaml.in
  install/gcp/gcp_installer.py
  install/gcp/installer/configs/config.py
  install/gcp/installer/forseti_client_installer.py
  install/gcp/installer/forseti_server_installer.py
  install/gcp/installer/util/gcloud.py
  install/gcp/installer/util/utils.py
Labels: cla: yes, status: in-progress

#1886 [Issue 1848] Update docker_unittest_forseti.sh
  install/scripts/docker_unittest_forseti.sh
Labels: cla: yes, status: in-progress

#1889 Fixing CrawlerTest to use Forseti Logging infrastructure
  tests/services/inventory/crawling_test.py
Labels: cla: yes, status: in-progress

#1855 Noting process for running unit tests in Docker after making changes
  _docs/_latest/develop/dev/testing.md
Labels: cla: yes, status: in-progress

#1890 [Issue #1848] Fixing logging to use Forsetting logging infrastructure.
  tests/services/dao_test.py
  tests/services/util/db.py
Labels: cla: yes, status: in-progress

#1892 Restart the server at the beginning of the cronjob, temp fix to #1832
  install/gcp/scripts/run_forseti.sh
  setup.py
Labels: cla: yes, status: in-progress

#1888 Retain masterAuth keys for container clusters, but redact actual data
  google/cloud/forseti/services/inventory/base/gcp.py
Labels: cla: yes

#1836 update stacktrace in broad excepts issue#1797
  google/cloud/forseti/common/util/replay.py
  google/cloud/forseti/common/util/threadpool.py
  google/cloud/forseti/services/dao.py
  google/cloud/forseti/services/inventory/base/resources.py
  google/cloud/forseti/services/inventory/crawler.py
  google/cloud/forseti/services/inventory/inventory.py
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/notifier/service.py
  google/cloud/forseti/services/scanner/service.py
  google/cloud/forseti/services/server_config/service.py
Labels: cla: yes, status: in-progress

#1895 Added try catch before uploading files to gcs bucket.
  google/cloud/forseti/common/util/file_uploader.py
Labels: cla: yes, status: in-progress

#1896 Add a flake8 test (pycodestyle) to check for pep8 related stye
  .travis.yml
  google/cloud/forseti/common/gcp_api/_base_repository.py
  google/cloud/forseti/common/gcp_api/cloud_resource_manager.py
  google/cloud/forseti/common/gcp_api/cloudbilling.py
  google/cloud/forseti/common/gcp_api/compute.py
  google/cloud/forseti/common/gcp_api/repository_mixins.py
  google/cloud/forseti/common/gcp_api/storage.py
  google/cloud/forseti/common/gcp_type/firewall_rule.py
  google/cloud/forseti/common/gcp_type/iam_policy.py
  google/cloud/forseti/common/gcp_type/log_sink.py
  google/cloud/forseti/common/gcp_type/service_account.py
  google/cloud/forseti/common/util/date_time.py
  google/cloud/forseti/common/util/errors.py
  google/cloud/forseti/common/util/regular_exp.py
  google/cloud/forseti/enforcer/batch_enforcer.py
  google/cloud/forseti/notifier/notifiers/inventory_summary.py
  google/cloud/forseti/scanner/audit/audit_logging_rules_engine.py
  google/cloud/forseti/scanner/audit/iam_rules_engine.py
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/notifier/service.py
  google/cloud/forseti/services/scanner/dao.py
  google/cloud/forseti/services/scanner/service.py
  google/cloud/forseti/stubs.py
  install/scripts/docker_pystyle_forseti.sh
  requirements.txt
Labels: cla: yes, status: in-progress

#1897 Updated logger to use exception() instead of error() when it's logging inside an except block.
  google/cloud/forseti/common/gcp_api/admin_directory.py
  google/cloud/forseti/common/gcp_api/cloudbilling.py
  google/cloud/forseti/common/gcp_api/cloudsql.py
  google/cloud/forseti/common/gcp_api/iam.py
  google/cloud/forseti/common/gcp_api/securitycenter.py
  google/cloud/forseti/common/gcp_api/servicemanagement.py
  google/cloud/forseti/common/gcp_api/stackdriver_logging.py
  google/cloud/forseti/common/gcp_api/storage.py
  google/cloud/forseti/common/util/date_time.py
  google/cloud/forseti/common/util/email.py
  google/cloud/forseti/common/util/file_loader.py
  google/cloud/forseti/common/util/metadata_server.py
  google/cloud/forseti/enforcer/enforcer.py
  google/cloud/forseti/enforcer/gce_firewall_enforcer.py
  google/cloud/forseti/enforcer/project_enforcer.py
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/notifier/notifiers/cscc_notifier.py
  google/cloud/forseti/notifier/notifiers/inventory_summary.py
  google/cloud/forseti/scanner/scanner.py
  google/cloud/forseti/scanner/scanner_builder.py
  google/cloud/forseti/services/base/config.py
  google/cloud/forseti/services/inventory/base/resources.py
  google/cloud/forseti/services/scanner/dao.py
  tests/common/gcp_api/admin_directory_test.py
  tests/notifier/notifiers/inventory_summary_test.py
Labels: cla: yes, status: in-progress

#1899 [Issue 1848] Mock out logger to fix pollution of test logs.
  tests/enforcer/gce_firewall_enforcer_test.py
Labels: cla: yes, status: in-progress

#1903 [Issue 1848] Mock out logger to fix almost all remaining instances of pollution of test logs. Remaining issuses involve server and will likely require some production refactoring.
  tests/enforcer/gce_firewall_enforcer_test.py
  tests/enforcer/project_enforcer_test.py
  tests/notifier/notifier_test.py
Labels: cla: yes, status: in-progress

#1906 Updated website with instructions to modify cron job
  _faq/installation_and_deployment/update-cron.md
Labels: cla: yes, status: in-progress

#1904 Fixes #1871, Update Enforcer to use the common gcp_api compute client.
  google/cloud/forseti/common/gcp_api/compute.py
  google/cloud/forseti/common/util/date_time.py
  google/cloud/forseti/enforcer/batch_enforcer.py
  google/cloud/forseti/enforcer/enforcer.py
  google/cloud/forseti/enforcer/gce_firewall_enforcer.py
  google/cloud/forseti/enforcer/project_enforcer.py
  tests/common/gcp_api/compute_test.py
  tests/common/util/date_time_test.py
  tests/enforcer/batch_enforcer_test.py
  tests/enforcer/enforcer_test.py
  tests/enforcer/gce_firewall_enforcer_test.py
  tests/enforcer/project_enforcer_test.py
  tests/enforcer/testing_constants.py
Labels: cla: yes, status: in-progress

#1893 Inventory and model compute snapshots
  google/cloud/forseti/common/gcp_api/compute.py
  google/cloud/forseti/services/inventory/base/gcp.py
  google/cloud/forseti/services/inventory/base/resources.py
  google/cloud/forseti/services/model/importer/importer.py
  tests/common/gcp_api/compute_test.py
  tests/common/gcp_api/test_data/fake_compute_responses.py
  tests/services/inventory/crawling_test.py
  tests/services/inventory/gcp_api_mocks.py
  tests/services/inventory/test_data/mock_gcp_results.py
  tests/services/model/importer/test_data/forseti-test.db
Labels: cla: yes

#1860 [Fixes #1859] Remove dependency on the _metadata server module from google.auth
  google/cloud/forseti/common/util/metadata_server.py
  tests/common/util/metadata_server_test.py
Labels: cla: yes, status: in-progress

#1912 Forsetisecurity.org Add snapshots to Resource Coverage on website
  _includes/docs/latest/resource-coverage.md
Labels: cla: yes

#1917 [Fixes #1910] Dev installer fix
  install/gcp/installer/forseti_installer.py
  install/gcp/installer/forseti_server_installer.py
  install/gcp/installer/util/gcloud.py
Labels: cla: yes

#1916 Removed sample from actual rule names
  rules/bigquery_rules.yaml
  rules/bucket_rules.yaml
  rules/cloudsql_rules.yaml
Labels: cla: yes, status: in-progress

#1884 [Fixes #1865] Fix bigquery scanner to respect resources
  google/cloud/forseti/scanner/audit/bigquery_rules_engine.py
  google/cloud/forseti/scanner/scanners/bigquery_scanner.py
  tests/scanner/audit/bigquery_rules_engine_test.py
  tests/scanner/audit/data/bigquery_test_rules_1.yaml
  tests/scanner/audit/data/bigquery_test_rules_2.yaml
  tests/scanner/audit/data/bigquery_test_rules_3.yaml
  tests/scanner/audit/data/bigquery_test_rules_4.yaml
  tests/scanner/scanners/bigquery_scanner_test.py
  tests/scanner/test_data/fake_bigquery_scanner_data.py
Labels: cla: yes, status: in-progress

#1924 Removed unused variable "service-account-gsuite" in the required section when generating the deployment template.
  deployment-templates/compute-engine/server/forseti-instance-server.py.schema
Labels: cla: yes, status: in-progress

#1905 Updated the group scanner to avoid scanning members with no rule
  google/cloud/forseti/scanner/scanners/groups_scanner.py
  tests/scanner/test_data/fake_group_rules.yaml
  tests/scanner/test_data/fake_groups_scanner_data.py
Labels: cla: yes, status: in-progress

#1921 [Issue 1848] Fix more log pollution of tests.
  tests/enforcer/project_enforcer_test.py
Labels: cla: yes, status: in-progress

#1933 Updated Documentation with G Suite optional
  _docs/_latest/setup/install.md
Labels: cla: yes, status: in-progress

#1934 Updated Installer with G Suite optional
  install/gcp/installer/util/constants.py
Labels: cla: yes, status: in-progress

#1940 Merge stable to dev
  README.md
  google/cloud/forseti/scanner/scanners/bigquery_scanner.py
  google/cloud/forseti/services/inventory/base/resources.py
  install/gcp/installer/util/gcloud.py
  install/gcp/scripts/run_forseti.sh
  tests/services/model/importer/test_data/forseti-test.db
Labels: cla: yes, status: in-progress

#1907 Improve CSCC usability
  google/cloud/forseti/notifier/notifiers/cscc_notifier.py
  tests/notifier/notifiers/cscc_notifier_test.py
Labels: cla: yes, status: in-progress

#1939 Add entry in FAQ for Terraform deployment
  _faq/installation_and_deployment/deploy-using-terraform.md
Labels: cla: yes

#1950 Updated website with Slack information and office hours
  _includes/docs/latest/get-help-question.md
Labels: cla: yes, status: in-progress

#1953 Removed unused constant MESSAGE_GSUITE_DATA_COLLECTION
  install/gcp/installer/util/constants.py
Labels: cla: yes, status: in-progress

#1922 Add billing accounts to log sink scanner
  google/cloud/forseti/common/gcp_type/billing_account.py
  google/cloud/forseti/common/gcp_type/resource.py
  google/cloud/forseti/common/gcp_type/resource_util.py
  google/cloud/forseti/scanner/audit/log_sink_rules_engine.py
  google/cloud/forseti/scanner/scanners/log_sink_scanner.py
  tests/common/gcp_type/billing_account_test.py
  tests/scanner/audit/data/log_sink_test_valid_rules.yaml
  tests/scanner/audit/log_sink_rules_engine_test.py
  tests/scanner/scanners/log_sink_scanner_test.py
  tests/scanner/test_data/fake_log_sink_scanner_data.py
Labels: cla: yes, status: in-progress

#1925 [Fixes #783] Support whitelist mode in Bigquery scanner
  google/cloud/forseti/common/util/regular_exp.py
  google/cloud/forseti/scanner/audit/bigquery_rules_engine.py
  rules/bigquery_rules.yaml
  tests/scanner/audit/bigquery_rules_engine_test.py
  tests/scanner/audit/data/bigquery_test_rules_5.yaml
  tests/scanner/audit/data/bigquery_test_rules_6.yaml
  tests/scanner/audit/data/bigquery_test_rules_7.yaml
  tests/scanner/test_data/fake_bigquery_scanner_data.py
Labels: cla: yes, status: in-progress

#1956 Merge stable to dev
  google/cloud/forseti/__init__.py
  install/gcp/installer/util/constants.py
Labels: cla: yes, status: in-progress

#1929 [Issue 1848] Fixing parameterized test to mock out logger to fix log pollution
  tests/enforcer/gce_firewall_enforcer_test.py
Labels: cla: yes, status: in-progress

#1961 Remove the AE for now while it's reworked.
  google/cloud/forseti/actions/__init__.py
  google/cloud/forseti/actions/action_config_validator.py
  google/cloud/forseti/actions/sample_action.py
  google/cloud/forseti/services/actions/__init__.py
  google/cloud/forseti/services/actions/action_engine.proto
  google/cloud/forseti/services/actions/action_engine.py
  tests/actions/__init__.py
  tests/actions/action_config_data.py
  tests/actions/action_config_validator_test.py
  tests/actions/action_engine_test.py
  tests/actions/test_data/__init__.py
  tests/actions/test_data/bad.yaml
  tests/actions/test_data/invalid_config.yaml
  tests/actions/test_data/valid_config.yaml
Labels: cla: yes, status: in-progress

#1959 Use the file_loader util method for safe yaml loading.
  google/cloud/forseti/scanner/scanners/groups_scanner.py
Labels: cla: yes, status: in-progress

#1958 Default non-existent fields in bigquery acl to glob
  google/cloud/forseti/scanner/audit/bigquery_rules_engine.py
  rules/bigquery_rules.yaml
  tests/scanner/audit/data/bigquery_test_rules_1.yaml
  tests/scanner/audit/data/bigquery_test_rules_2.yaml
  tests/scanner/audit/data/bigquery_test_rules_3.yaml
  tests/scanner/audit/data/bigquery_test_rules_4.yaml
  tests/scanner/audit/data/bigquery_test_rules_5.yaml
  tests/scanner/audit/data/bigquery_test_rules_6.yaml
  tests/scanner/audit/data/bigquery_test_rules_7.yaml
Labels: cla: yes, status: in-progress

#1964 Added a new rule to scan for bucket with allUsers in IAM policy
  rules/iam_rules.yaml
Labels: cla: yes, status: in-progress

#1965 Removed upgrade option
  install/gcp/installer/forseti_server_installer.py
  install/gcp/installer/util/merge_engine.py
  install/gcp/installer/util/upgradeable_resources.py
  tests/gcp/installer/util/functional_test.py
  tests/gcp/installer/util/merge_engine_test.py
  tests/gcp/installer/util/test_data/expected_merged_bucket_rules.yaml
  tests/gcp/installer/util/test_data/expected_merged_firewall_rules.yaml
  tests/gcp/installer/util/test_data/expected_merged_forseti_conf_server_from_1.1.10.yaml
  tests/gcp/installer/util/test_data/expected_merged_forseti_conf_server_from_1.1.6.yaml
  tests/gcp/installer/util/test_data/expected_merged_forseti_conf_server_from_1.1.9.yaml
  tests/gcp/installer/util/test_data/expected_merged_group_rules.yaml
  tests/gcp/installer/util/test_data/expected_merged_iam_rules.yaml
  tests/gcp/installer/util/test_data/merge_from_bucket_rules.yaml
  tests/gcp/installer/util/test_data/merge_from_firewall_rules.yaml
  tests/gcp/installer/util/test_data/merge_from_forseti_conf_1.1.10.yaml
  tests/gcp/installer/util/test_data/merge_from_forseti_conf_1.1.6.yaml
  tests/gcp/installer/util/test_data/merge_from_forseti_conf_1.1.9.yaml
  tests/gcp/installer/util/test_data/merge_from_group_rules.yaml
  tests/gcp/installer/util/test_data/merge_from_iam_rules.yaml
  tests/gcp/installer/util/test_data/merge_to_bucket_rules.yaml
  tests/gcp/installer/util/test_data/merge_to_firewall_rules.yaml
  tests/gcp/installer/util/test_data/merge_to_forseti_conf_server.yaml
  tests/gcp/installer/util/test_data/merge_to_group_rules.yaml
  tests/gcp/installer/util/test_data/merge_to_iam_rules.yaml
Labels: cla: yes, status: in-progress

#1967 more APIs require enabling
  install/gcp/installer/util/constants.py
Labels: cla: yes

#1966 Update upgrade instructions
  _docs/_latest/setup/upgrade.md
Labels: cla: yes, status: in-progress

#1969 Handle SSH failure gracefully during the installation process
  install/gcp/installer/forseti_installer.py
  install/gcp/installer/util/constants.py
  install/gcp/installer/util/gcloud.py
  install/gcp/installer/util/installer_errors.py
Labels: cla: yes, status: in-progress

#1970 adding Michael Capicotto as a contributor
  CONTRIBUTORS
Labels: cla: no

#1975 Add support for billing_account to IAM scanner
  google/cloud/forseti/scanner/scanners/iam_rules_scanner.py
  tests/scanner/audit/data/test_rules.py
  tests/scanner/audit/iam_rules_engine_test.py
  tests/scanner/scanners/iam_rules_scanner_test.py
Labels: cla: yes, status: in-progress
