Repository forseti-security/forseti-security, pull requests merged in 2018-07, with the labels that each got.

#1755 Pin idna to version 2.6 and pip to version 9.0.3
  deployment-templates/compute-engine/forseti-instance.py
  setup.py
Labels: cla: yes, status: in-progress

#1756 Removed the execution of run_forseti.sh from the startup script
  deployment-templates/compute-engine/forseti-instance.py
Labels: cla: yes, status: in-progress

#1759 Updated the dataset type_name to use dataset_policy/{dataset_id} format.
  google/cloud/forseti/services/model/importer/importer.py
Labels: cla: yes, status: in-progress

#1762 Run cloudsqlproxy service as root
  install/gcp/scripts/initialize_forseti_services.sh
Labels: cla: yes, status: in-progress

#1757 Tidy-Up CSCC API
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/common/gcp_api/_base_repository.py
  google/cloud/forseti/common/gcp_api/_supported_apis.py
  google/cloud/forseti/common/gcp_api/repository_mixins.py
  google/cloud/forseti/common/gcp_api/securitycenter.py
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/notifier/notifiers/cscc_notifier.py
  tests/common/gcp_api/base_repository_test.py
  tests/common/gcp_api/securitycenter_test.py
  tests/common/gcp_api/test_data/fake_securitycenter_responses.py
  tests/notifier/notifiers/cscc_notifier_test.py
Labels: cla: yes, status: in-progress

#1760 update iter_foo and fetch_foo issue#1702
  google/cloud/forseti/services/inventory/base/gcp.py
Labels: cla: yes, status: in-progress

#1751 Fix broken links on README.md
  README.md
Labels: cla: yes, status: in-progress

#1764 Merge stable to dev
  install/gcp/scripts/initialize_forseti_services.sh
Labels: cla: yes, status: in-progress

#1766 Add Compute Engine disks to crawler and data model.
  google/cloud/forseti/services/inventory/base/gcp.py
  google/cloud/forseti/services/inventory/base/resources.py
  google/cloud/forseti/services/model/importer/importer.py
  tests/services/inventory/crawling_test.py
  tests/services/inventory/gcp_api_mocks.py
  tests/services/inventory/test_data/mock_gcp_results.py
  tests/services/model/importer/test_data/forseti-test.db
Labels: cla: yes, status: in-progress

#1769 Added 2.0 upgrade instruction
  _docs/_latest/setup/upgrade.md
  _docs/v1.1/quickstarts/scanner/index.md
Labels: cla: yes, status: in-progress

#1772 Added missing gsuite scope
  _docs/_latest/configure/inventory/gsuite.md
  _docs/v2.0/configure/inventory/gsuite.md
Labels: cla: yes, status: in-progress

#1773 Updated broken urls
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  google/cloud/forseti/common/gcp_api/admin_directory.py
  install/gcp/installer/util/utils.py
Labels: cla: yes, status: in-progress

#1774 Upgrade instructions review
  _docs/_latest/setup/upgrade.md
Labels: cla: yes, status: in-progress

#1777 Alpha sort the scanner maps issue#1654
  google/cloud/forseti/scanner/scanner_requirements_map.py
Labels: cla: yes, status: in-progress

#1779 Added compute engine disk resource
  _includes/docs/latest/resource-coverage.md
Labels: cla: yes, status: in-progress

#1778 Update CSCC doc for API mode
  _docs/_latest/configure/notifier/index.md
Labels: cla: yes, status: in-progress

#1781 Updated variable in the configs yaml file
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
Labels: cla: yes, status: in-progress

#1788 Fix full_res_name value when the root_resource is a project or a folder
  google/cloud/forseti/services/model/importer/importer.py
Labels: cla: yes

#1791 Update our versioning scheme to follow the Semantic Versioning standard.
  _docs/_latest/develop/branch-management.md
  _docs/v2.0/develop/branch-management.md
  _docs/v2.1/develop/branch-management.md
Labels: cla: yes, status: in-progress

#1793 Merge forsetisecurity.org-dev to forsetisecurity.org
  scripts/build_doc_version_index.sh
Labels: cla: yes, status: in-progress

#1794 Updated readme.md
  README.md
Labels: cla: yes, status: in-progress

#1795 Updated app.yaml to redirect properly
  app.yaml
Labels: cla: yes, status: in-progress

#1796 Fixed the keys of Memory.mem to avoid key conflicts. Some GCP reso…
  google/cloud/forseti/services/inventory/base/storage.py
Labels: cla: yes, status: in-progress, type: bug

#1798 Fixed version redirect issues
  _includes/site/layout/docs/tabs.html
  app.yaml
Labels: cla: yes, status: in-progress

#1747 Add a scanner for Log Sinks
  configs/server/forseti_conf_server.yaml.in
  google/cloud/forseti/common/data_access/violation_map.py
  google/cloud/forseti/common/gcp_type/log_sink.py
  google/cloud/forseti/common/gcp_type/resource.py
  google/cloud/forseti/scanner/audit/log_sink_rules_engine.py
  google/cloud/forseti/scanner/scanner_requirements_map.py
  google/cloud/forseti/scanner/scanners/log_sink_scanner.py
  rules/log_sink_rules.yaml
  tests/common/gcp_type/log_sink_test.py
  tests/scanner/audit/data/log_sink_test_invalid_rules.yaml
  tests/scanner/audit/data/log_sink_test_valid_rules.yaml
  tests/scanner/audit/log_sink_rules_engine_test.py
  tests/scanner/scanners/log_sink_scanner_test.py
  tests/scanner/test_data/fake_log_sink_scanner_data.py
Labels: cla: yes, status: in-progress

#1799 Update forsetisecurity.org-dev faqs for VM instances security updates…
  _faq/installation_and_deployment/forseti VM instance security updates.md
Labels: cla: yes, status: in-progress

#1803 Shorten the violation id hash.
  google/cloud/forseti/notifier/notifiers/cscc_notifier.py
  tests/notifier/notifiers/cscc_notifier_test.py
Labels: cla: yes, status: in-progress

#1808 Update CSCC notifier documentation to list the additional requirements for CSCC
  _docs/_latest/configure/notifier/index.md
Labels: cla: yes, status: in-progress

#1809 Cherry picking commit "Shorten the violation id hash. (#1803)" into stable
  google/cloud/forseti/notifier/notifiers/cscc_notifier.py
  tests/notifier/notifiers/cscc_notifier_test.py
Labels: cla: yes, status: in-progress

#1807 Fix Forseti.org dev latest versioning
  _includes/site/layout/docs/tabs.html
Labels: cla: yes, status: in-progress

#1810 Update website with recent changes. (CSCC requirements)
  _docs/_latest/configure/notifier/index.md
  _faq/installation_and_deployment/forseti VM instance security updates.md
  _includes/site/layout/docs/tabs.html
Labels: cla: yes, status: in-progress

#1804 Adding information about building the website server locally for development
  _docs/_latest/develop/get-help.md
  _docs/_latest/develop/index.md
  _docs/_latest/develop/website.md
Labels: cla: no, status: in-progress

#1813 Fixing typo in org policy permission configuration
  _includes/docs/latest/deployment-prerequisites.md
Labels: cla: yes, status: in-progress

#1812 Noting the updated G Suite Domain-wide Delegation screen.
  _docs/_latest/configure/inventory/gsuite.md
Labels: cla: yes, status: in-progress

#1814 Updating documentation as `service-management enable` is now `services enable`
  _includes/docs/latest/deployment-prerequisites.md
Labels: cla: yes, status: in-progress

#1818 Adding some additional clarification to setup process, specifically g…
  _includes/docs/latest/deployment-prerequisites.md
Labels: cla: yes, status: in-progress

#1819 Adding clarifying details for CloudSQL setup
  _includes/docs/latest/setup-cloudsql.md
Labels: cla: yes, status: in-progress

#1823 Documenting solution to virtualenv issues on clean Linux install
  _docs/_latest/develop/dev/setup.md
Labels: cla: yes, status: in-progress

#1824 Updated installation instructions to include steps to install server instance only
  _docs/_latest/setup/install.md
  _docs/v2.0/setup/install.md
  _docs/v2.1/setup/install.md
Labels: cla: yes, status: in-progress

#1831 Increment version to 1.1.12 for release.
  google/cloud/security/__init__.py
Labels: cla: yes, status: in-progress
