Repository forseti-security/forseti-security, pull requests merged in 2018-04, with the labels that each got.

#1323 Enable IAM and firewall notifications by default
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
Labels: cla: yes, status: in-progress

#1318 Update the storage API client to detect when user project required.
  google/cloud/forseti/common/gcp_api/storage.py
  google/cloud/forseti/common/util/metadata_server.py
  setup/gcp/installer/util/constants.py
  tests/common/gcp_api/storage_test.py
  tests/common/gcp_api/test_data/fake_storage_responses.py
  tests/common/util/metadata_server_test.py
Labels: cla: yes, status: in-progress

#1331 Fix build script for Travis CI
  travis/jekyll_build.sh
Labels: cla: yes

#1332 Fix all broken doc links
  _docs/_latest/concepts/architecture.md
  _docs/_latest/concepts/index.md
  _docs/_latest/concepts/models.md
  _docs/_latest/concepts/service-accounts.md
  _docs/_latest/configure/gsuite-group-collection.md
  _docs/_latest/configure/index.md
  _docs/_latest/develop/index.md
  _docs/_latest/develop/testing.md
  _docs/_latest/setup/index.md
  _docs/_latest/setup/install.md
  _docs/_latest/setup/upgrade.md
  _docs/_latest/use/cli.md
  _docs/_latest/use/index.md
  _docs/_latest/use/inventory.md
  _faq/installation_and_deployment/change-setup.md
  _faq/installation_and_deployment/update-forseti.md
  _faq/installation_and_deployment/which-deployment.md
  about/index.md
Labels: cla: yes

#1335 Fix FAQ page rendering
  _includes/site/faq/qa_item.html
  _plugins/third_party/liquify/LICENSE.txt
  _plugins/third_party/liquify/liquify.rb
Labels: cla: yes

#1336 Add commit hash and date to docs footer
  _includes/site/layout/base/footer.html
  _plugins/git_commit_info.rb
Labels: cla: yes

#1337 Docs/responsive images
  .gitignore
  Gemfile
  _config.yml
  _docs/_latest/concepts/forseti-service-accounts.md
  _docs/_latest/configure/gsuite-group-collection.md
  _docs/_latest/configure/scanner/policy-violations.md
  _docs/v1.1/howto/configure/gsuite-group-collection.md
  _docs/v1.1/quickstarts/scanner/policy-violations.md
  _includes/responsive_image/template.html
Labels: cla: yes

#1306 Reformat documentation homepage
  _data/homepage_promo_items.yml
  _includes/site/layout/base/footer/links.html
  _layouts/homepage.html
  _sass/layouts/_homepage.scss
  index.html
  index.md
Labels: cla: yes

#1333 Update the CONTRIBUTORS file
  CONTRIBUTORS
Labels: cla: yes, status: in-progress

#1344 Updated slack webhook notifier
  google/cloud/forseti/notifier/notifiers/slack_webhook.py
  tests/notifier/notifiers/slack_webhook_test.py
Labels: cla: yes, status: in-progress

#1342 Start forseti service and cloudsql service with ubuntu instead of root
  setup/gcp/scripts/initialize_forseti_services.sh
Labels: cla: yes, status: in-progress

#1345 Fix IAP Violations not saved to GCS
  configs/server/forseti_conf_server.yaml.in
Labels: status: in-progress

#1350 Include data_format explicitly in notifier config.
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
Labels: cla: yes, status: in-progress

#1351 Add flag to enable debug mode and suppress crawler's errors & warnings with it.
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/inventory/inventory.proto
  google/cloud/forseti/services/inventory/service.py
  google/cloud/forseti/services/server.py
  tests/services/cli_test.py
Labels: cla: yes, status: in-progress

#1364 Update rule files after installation
  deployment-templates/compute-engine/server/forseti-instance-server.py
Labels: cla: yes, status: in-progress

#1365 Commented out iam custom rules
  rules/iam_rules.yaml
Labels: cla: yes, status: in-progress

#1367 Added email notifications to all the resources
  configs/server/forseti_conf_server.yaml.in
Labels: cla: yes, status: in-progress

#1221 Added setup/upgrade.md
  _docs/_latest/setup/upgrade.md
Labels: cla: no, status: in-progress

#1369 Disable iap custom rule
  rules/iap_rules.yaml
Labels: cla: yes, status: in-progress

#1370 Make the default instance network scanner not throw off violation
  rules/instance_network_interface_rules.yaml
Labels: cla: yes, status: in-progress

#1371 Manually merge 2.0-dev into RC2.
  configs/server/forseti_conf_server.yaml.in
  deployment-templates/compute-engine/server/forseti-instance-server.py
  rules/iam_rules.yaml
  rules/iap_rules.yaml
  setup/gcp/installer/util/gcloud.py
Labels: cla: yes, status: in-progress

#1380 Upgrader updates
  setup/gcp/installer/forseti_server_installer.py
  setup/gcp/installer/util/constants.py
  setup/gcp/installer/util/files.py
  setup/gcp/installer/util/upgradeable_resources.py
  setup/gcp/installer/util/utils.py
Labels: cla: yes, status: in-progress

#1386 Merge 2.0-rc2 into 2.0-dev
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  deployment-templates/compute-engine/server/forseti-instance-server.py
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/inventory/inventory.proto
  google/cloud/forseti/services/inventory/service.py
  google/cloud/forseti/services/server.py
  rules/instance_network_interface_rules.yaml
  setup/gcp/installer/forseti_server_installer.py
  setup/gcp/installer/util/constants.py
  setup/gcp/installer/util/files.py
  setup/gcp/installer/util/upgradeable_resources.py
  setup/gcp/installer/util/utils.py
  tests/services/cli_test.py
Labels: cla: yes, status: in-progress

#1230 Added quickstarts/explain/index.md
  _docs/_latest/quickstarts/explain/index.md
Labels: cla: no, status: in-progress

#1390 Updated importer to handle duplicate gcp_inventory records
  google/cloud/forseti/services/model/importer/importer.py
  tests/services/inventory/test_data/mock_gcp_results.py
  tests/services/model/importer/test_data/forseti-test.db
Labels: cla: yes, status: in-progress

#1393 Making model creation using import_as blocks
  google/cloud/forseti/services/inventory/crawler.py
  google/cloud/forseti/services/inventory/inventory.py
  setup/gcp/scripts/run_forseti.sh
Labels: cla: yes, status: in-progress

#1402 removed server and client folder under configs/ on gcs
  deployment-templates/compute-engine/client/forseti-instance-client.py
  deployment-templates/compute-engine/server/forseti-instance-server.py
  setup/gcp/installer/util/constants.py
  setup/gcp/installer/util/files.py
  setup/gcp/scripts/run_forseti.sh
Labels: cla: yes, status: in-progress

#1403 Do not set final_message when the queue ends
  google/cloud/forseti/services/inventory/inventory.py
  tests/services/api_tests/inventory_test.py
Labels: cla: yes, status: in-progress

#1400 Added loggings around gsuite api
  google/cloud/forseti/common/gcp_api/admin_directory.py
  tests/common/gcp_api/admin_directory_test.py
Labels: cla: yes, status: in-progress

#1404 Updated step to output resourceType/resourceKey
  google/cloud/forseti/services/inventory/inventory.py
Labels: cla: yes, status: in-progress

#1408 Hide options to create empty data model, default model source to inventory and rename --id flag to --inventory_index_id
  google/cloud/forseti/services/cli.py
  tests/services/cli_test.py
Labels: cla: yes, status: in-progress

#1407 Added user "forseti-db-admin" to the database and switch to using "forseti-db-admin" to connect to the db in the application
  deployment-templates/cloudsql/cloudsql-user.py
  deployment-templates/deploy-forseti-server.yaml.in
  setup/gcp/scripts/initialize_forseti_services.sh
Labels: cla: yes, status: in-progress

#1412 Rename sql instance
  setup/gcp/installer/configs/server_config.py
Labels: cla: yes, status: in-progress

#1411 Add a scanner for Enabled APIs
  configs/server/forseti_conf_server.yaml.in
  google/cloud/forseti/common/data_access/violation_map.py
  google/cloud/forseti/scanner/audit/enabled_apis_rules_engine.py
  google/cloud/forseti/scanner/scanner_requirements_map.py
  google/cloud/forseti/scanner/scanners/enabled_apis_scanner.py
  google/cloud/forseti/services/model/importer/importer.py
  rules/enabled_apis_rules.yaml
  tests/scanner/audit/data/enabled_apis_test_rules_1.yaml
  tests/scanner/audit/data/enabled_apis_test_rules_2.yaml
  tests/scanner/audit/data/enabled_apis_test_rules_3.yaml
  tests/scanner/audit/enabled_apis_rules_engine_test.py
  tests/scanner/scanners/enabled_apis_scanner_test.py
  tests/scanner/test_data/fake_enabled_apis_scanner_data.py
Labels: cla: yes, status: in-progress

#1414 Added dufton as a contributor to Forseti
  CONTRIBUTORS
Labels: cla: yes, status: in-progress

#1419 Specified pip version to be 9.0.3
  deployment-templates/compute-engine/forseti-instance.py
  google/cloud/security/common/gcp_api/_base_repository.py
  google/cloud/security/common/gcp_api/admin_directory.py
  google/cloud/security/common/gcp_api/appengine.py
  google/cloud/security/common/gcp_api/bigquery.py
  google/cloud/security/common/gcp_api/cloud_resource_manager.py
  google/cloud/security/common/gcp_api/cloudbilling.py
  google/cloud/security/common/gcp_api/cloudsql.py
  google/cloud/security/common/gcp_api/compute.py
  google/cloud/security/common/gcp_api/container.py
  google/cloud/security/common/gcp_api/iam.py
  google/cloud/security/common/gcp_api/storage.py
  google/cloud/security/enforcer/gce_firewall_enforcer.py
Labels: cla: yes, status: in-progress

#1423 Replace deprecated oauth2client with google.auth library.
  deployment-templates/compute-engine/client/forseti-instance-client.py
  deployment-templates/compute-engine/server/forseti-instance-server.py
  google/cloud/forseti/common/gcp_api/_base_repository.py
  google/cloud/forseti/common/gcp_api/admin_directory.py
  google/cloud/forseti/common/gcp_api/api_helpers.py
  setup.py
  setup/docker/forseti
  tests/common/gcp_api/admin_directory_test.py
  tests/common/gcp_api/api_helpers_test.py
  tests/common/gcp_api/appengine_test.py
  tests/common/gcp_api/base_repository_test.py
  tests/common/gcp_api/bigquery_test.py
  tests/common/gcp_api/cloud_resource_manager_test.py
  tests/common/gcp_api/cloudbilling_test.py
  tests/common/gcp_api/cloudsql_test.py
  tests/common/gcp_api/compute_test.py
  tests/common/gcp_api/container_test.py
  tests/common/gcp_api/iam_test.py
  tests/common/gcp_api/servicemanagement_test.py
  tests/common/gcp_api/storage_test.py
  tests/common/gcp_api/test_data/fake_key_file.py
  tests/common/util/file_loader_test.py
  tests/common/util/replay_test.py
  tests/enforcer/gce_firewall_enforcer_test.py
  tests/enforcer/project_enforcer_test.py
  tests/services/cli_test.py
Labels: cla: yes, status: in-progress

#1422 Rename "finding" references to "CSCC" now that it's launched publicly.
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/common/util/string_formats.py
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/notifier/notifiers/cscc_notifier.py
  tests/notifier/notifiers/cscc_notifier_test.py
Labels: cla: yes, status: in-progress

#1421 Allow Inventory crawler to run without Org access.
  google/cloud/forseti/services/inventory/base/resources.py
  tests/services/inventory/crawling_test.py
  tests/services/inventory/gcp_api_mocks.py
  tests/services/inventory/test_data/mock_gcp_results.py
Labels: cla: yes, status: in-progress

#1433 Minor update to the docker file
  setup/docker/forseti
Labels: cla: yes, status: in-progress

#1440 Data model handle duplicate data (member & membership)
  deployment-templates/compute-engine/client/forseti-instance-client.py
  deployment-templates/compute-engine/server/forseti-instance-server.py
  google/cloud/forseti/services/model/importer/importer.py
  setup/docker/forseti
  tests/services/inventory/crawling_test.py
  tests/services/inventory/test_data/mock_gcp_results.py
  tests/services/model/importer/test_data/forseti-test.db
Labels: cla: yes, status: in-progress

#1439 Make server command line arg processing more robust
  google/cloud/forseti/services/server.py
  tests/services/server_test.py
Labels: cla: yes, status: in-progress

#1434 Fix naming of enabled APIs violation type
  google/cloud/forseti/common/data_access/violation_map.py
  tests/scanner/test_data/fake_enabled_apis_scanner_data.py
Labels: cla: yes, status: in-progress

#1416 Inventory summary notification upload to GCS
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/common/data_access/csv_writer.py
  google/cloud/forseti/common/util/file_uploader.py
  google/cloud/forseti/common/util/string_formats.py
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/notifier/notifiers/base_notification.py
  google/cloud/forseti/notifier/notifiers/email_inventory_snapshot_summary.py
  google/cloud/forseti/notifier/notifiers/email_scanner_summary.py
  google/cloud/forseti/notifier/notifiers/gcs_violations.py
  google/cloud/forseti/notifier/notifiers/inventory_summary.py
  google/cloud/forseti/services/inventory/storage.py
  tests/notifier/notifier_test.py
  tests/notifier/notifiers/email_inventory_snapshot_summary_test.py
  tests/notifier/notifiers/email_scanner_summary_test.py
  tests/notifier/notifiers/gcs_violations_test.py
  tests/notifier/notifiers/inventory_summary_test.py
  tests/services/inventory/storage_test.py
Labels: cla: yes, status: in-progress

#1453 Link commit hash in footer to github
  _includes/site/layout/base/footer.html
  _sass/components/_footer.scss
Labels: cla: yes

#1452 Fix header layout issues on mobile
  _includes/site/layout/docs/tabs.html
  _sass/layouts/_docs.scss
Labels: cla: yes

#1451 Disable visual building toc
  _includes/site/layout/base/scripts.html
Labels: cla: yes

#1450 Add better visual separation for left nav items
  _sass/components/_left_sidebar.scss
Labels: cla: yes

#1448 Improve docs readability
  _sass/base/_typography.scss
  css/all.scss
Labels: cla: yes

#1445 Rate limiter updates
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/common/gcp_api/admin_directory.py
  google/cloud/forseti/common/gcp_api/api_helpers.py
  google/cloud/forseti/common/gcp_api/appengine.py
  google/cloud/forseti/common/gcp_api/bigquery.py
  google/cloud/forseti/common/gcp_api/cloud_resource_manager.py
  google/cloud/forseti/common/gcp_api/cloudbilling.py
  google/cloud/forseti/common/gcp_api/cloudsql.py
  google/cloud/forseti/common/gcp_api/compute.py
  google/cloud/forseti/common/gcp_api/container.py
  google/cloud/forseti/common/gcp_api/iam.py
  google/cloud/forseti/common/gcp_api/servicemanagement.py
  setup/gcp/installer/forseti_server_installer.py
  setup/gcp/scripts/initialize_forseti_services.sh
  tests/common/gcp_api/admin_directory_test.py
  tests/common/gcp_api/appengine_test.py
  tests/common/gcp_api/bigquery_test.py
  tests/common/gcp_api/cloud_resource_manager_test.py
  tests/common/gcp_api/cloudbilling_test.py
  tests/common/gcp_api/cloudsql_test.py
  tests/common/gcp_api/compute_test.py
  tests/common/gcp_api/container_test.py
  tests/common/gcp_api/iam_test.py
  tests/common/gcp_api/servicemanagement_test.py
  tests/gcp/installer/util/test_data/expected_merged_forseti_conf_server_from_1.1.10.yaml
  tests/gcp/installer/util/test_data/expected_merged_forseti_conf_server_from_1.1.6.yaml
  tests/gcp/installer/util/test_data/expected_merged_forseti_conf_server_from_1.1.9.yaml
  tests/gcp/installer/util/test_data/merge_to_forseti_conf_server.yaml
Labels: cla: yes, status: in-progress

#1446 Updated installer to output the frequency of Forseti run.
  deployment-templates/compute-engine/server/forseti-instance-server.py
  deployment-templates/deploy-forseti-server.yaml.in
  setup/gcp/installer/forseti_server_installer.py
  setup/gcp/installer/util/constants.py
Labels: cla: yes, status: in-progress

#1456 Installer updated to use pip 10.0.1 (default cloudshell version)
  setup/gcp/run_forseti_installer.py
Labels: cla: yes, status: in-progress

#1449 Apply rouge highlighting to inline code
  _sass/rouge/_github_codeblock.scss
Labels: cla: yes, status: in-progress

#1352 Only notify of violations from the most recent scanner run
  google/cloud/forseti/common/util/index_state.py
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/notifier/notifiers/cscc_notifier.py
  google/cloud/forseti/scanner/scanner.py
  google/cloud/forseti/scanner/scanners/base_scanner.py
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/scanner/dao.py
  google/cloud/forseti/services/scanner/service.py
  tests/notifier/notifier_test.py
  tests/notifier/notifiers/cscc_notifier_test.py
  tests/scanner/scanner_test.py
  tests/services/scanner/scanner_dao_test.py
Labels: cla: yes, status: in-progress

#1444 Updated importer to use 2 sessions
  google/cloud/forseti/services/dao.py
  google/cloud/forseti/services/db.py
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/model/modeller.py
  tests/services/model/importer/importer_test.py
  tests/services/model/importer/test_data/forseti-test.db
Labels: cla: yes, status: in-progress

#1457 merge 2.0 handle duplicate gcp response into rc2
  google/cloud/forseti/services/dao.py
  google/cloud/forseti/services/db.py
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/model/modeller.py
  setup/gcp/scripts/run_forseti.sh
  tests/services/inventory/crawling_test.py
  tests/services/inventory/test_data/mock_gcp_results.py
  tests/services/model/importer/importer_test.py
  tests/services/model/importer/test_data/forseti-test.db
Labels: cla: yes, status: in-progress

#1447 Fix docstring formatting issues
  google/cloud/forseti/common/gcp_api/api_helpers.py
  google/cloud/forseti/common/gcp_api/appengine.py
  google/cloud/forseti/common/gcp_api/bigquery.py
  google/cloud/forseti/common/gcp_api/compute.py
  google/cloud/forseti/common/gcp_api/container.py
  google/cloud/forseti/common/gcp_type/resource_util.py
  google/cloud/forseti/common/util/regular_exp.py
  google/cloud/forseti/common/util/relationship.py
  google/cloud/forseti/enforcer/batch_enforcer.py
  google/cloud/forseti/enforcer/gce_firewall_enforcer.py
  google/cloud/forseti/enforcer/project_enforcer.py
  google/cloud/forseti/scanner/audit/forwarding_rule_rules_engine.py
  google/cloud/forseti/scanner/audit/iam_rules_engine.py
  google/cloud/forseti/services/explain/explainer.py
  google/cloud/forseti/services/inventory/storage.py
Labels: cla: yes, status: in-progress

#1459 Hand patch the inventory summary PR into RC2
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/common/data_access/csv_writer.py
  google/cloud/forseti/common/util/file_uploader.py
  google/cloud/forseti/common/util/string_formats.py
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/notifier/notifiers/base_notification.py
  google/cloud/forseti/notifier/notifiers/email_inventory_snapshot_summary.py
  google/cloud/forseti/notifier/notifiers/email_scanner_summary.py
  google/cloud/forseti/notifier/notifiers/gcs_violations.py
  google/cloud/forseti/notifier/notifiers/inventory_summary.py
  google/cloud/forseti/services/inventory/storage.py
  tests/notifier/notifier_test.py
  tests/notifier/notifiers/email_inventory_snapshot_summary_test.py
  tests/notifier/notifiers/email_scanner_summary_test.py
  tests/notifier/notifiers/gcs_violations_test.py
  tests/notifier/notifiers/inventory_summary_test.py
  tests/services/inventory/storage_test.py
Labels: cla: yes, status: in-progress

#1460 Added encoding to make the MySQL String column case sensitive
  google/cloud/forseti/services/dao.py
Labels: cla: yes, status: in-progress

#1462 merge 2.0 handle duplicate gcp response into rc2
  google/cloud/forseti/services/dao.py
Labels: cla: yes, status: in-progress

#1471 Unset default gcs path in server config for inventory summary.
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
Labels: cla: yes, status: in-progress

#1469 Fix explainer CLI tracebacks
  google/cloud/forseti/services/cli.py
  tests/services/cli_test.py
Labels: cla: yes, status: in-progress

#1463 Port retention_days to 2.0
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/inventory/inventory.proto
  google/cloud/forseti/services/inventory/inventory.py
  google/cloud/forseti/services/inventory/service.py
  google/cloud/forseti/services/inventory/storage.py
  tests/services/inventory/purge_inventory_test.py
Labels: cla: yes, status: in-progress

#1478 Merge rc2 to 2.0 dev
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/services/dao.py
  google/cloud/forseti/services/db.py
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/model/modeller.py
  setup/docker/forseti
  setup/gcp/run_forseti_installer.py
  setup/gcp/scripts/run_forseti.sh
  tests/notifier/notifier_test.py
  tests/services/inventory/crawling_test.py
  tests/services/inventory/test_data/mock_gcp_results.py
  tests/services/model/importer/importer_test.py
  tests/services/model/importer/test_data/forseti-test.db
Labels: cla: yes, status: in-progress

#1479 Make the inventory purge runnable from the cron job.
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/inventory/inventory.proto
  google/cloud/forseti/services/inventory/inventory.py
  google/cloud/forseti/services/server.py
  setup/gcp/scripts/run_forseti.sh
  tests/services/api_tests/inventory_test.py
  tests/services/inventory/crawling_test.py
  tests/services/inventory/purge_inventory_test.py
Labels: cla: yes, status: in-progress
