Repository forseti-security/forseti-security, pull requests merged in 2018-06, with the labels that each got.

#1625 Update architecture.md
  _docs/_latest/concepts/architecture.md
Labels: cla: yes, status: in-progress

#1626 Arch images update
  images/docs/concepts/forseti-architecture.png
  images/docs/concepts/service-account-architecture.png
Labels: cla: yes, status: in-progress

#1630 Service account key scanner
  google/cloud/forseti/common/data_access/violation_map.py
  google/cloud/forseti/common/gcp_type/resource.py
  google/cloud/forseti/common/gcp_type/service_account.py
  google/cloud/forseti/scanner/audit/service_account_key_rules_engine.py
  google/cloud/forseti/scanner/scanner_requirements_map.py
  google/cloud/forseti/scanner/scanners/service_account_key_scanner.py
  rules/service_account_key_rules.yaml
  tests/scanner/scanners/data/service_account_key_test_rules.yaml
  tests/scanner/scanners/service_account_key_test.py
Labels: cla: yes, status: in-progress

#1635 Updated instruction message in installer, removed unused flag
  install/gcp/gcp_installer.py
  install/gcp/installer/forseti_server_installer.py
  install/gcp/installer/util/constants.py
Labels: cla: yes, status: in-progress

#1628 Review docs under category "configure"
  _docs/_latest/configure/configuring-forseti.md
  _docs/_latest/configure/email-notification.md
  _docs/_latest/configure/forseti/index.md
  _docs/_latest/configure/gsuite-group-collection.md
  _docs/_latest/configure/gsuite.md
  _docs/_latest/configure/index.md
  _docs/_latest/configure/inventory/index.md
  _docs/_latest/configure/notifier/index.md
  _docs/_latest/configure/scanner/default-rules.md
  _docs/_latest/configure/scanner/descriptions.md
  _docs/_latest/configure/scanner/index.md
  _docs/_latest/configure/scanner/policy-violations.md
  _docs/_latest/configure/scanner/rule_engine.md
  _docs/_latest/configure/scanner/rules.md
  _docs/_latest/develop/dev-setup.md
  _docs/_latest/develop/testing.md
  _docs/_latest/setup/install.md
  _docs/_latest/setup/upgrade.md
  _docs/_latest/use/inventory.md
  _docs/_latest/use/scanner.md
  _docs/v1.1/howto/configure/gsuite-group-collection.md
  _docs/v1.1/howto/configure/index.md
  _docs/v1.1/howto/index.md
  _docs/v1.1/quickstarts/scanner/descriptions.md
  _faq/installation_and_deployment/change-setup.md
  _faq/installation_and_deployment/update-forseti.md
  _faq/installation_and_deployment/which-deployment.md
  _faq/resource/resources.md
  _includes/docs/latest/deployment_prerequisites.md
  _includes/docs/latest/min_conf_settings.md
  _includes/docs/v1.1/howto/deployment_prerequisites.md
  _includes/docs/v1.1/resources.md
  about/index.md
  images/docs/configuration/service_account_edit.png
  images/docs/configuration/service_account_enable_dwd.png
  images/docs/configuration/service_account_page.png
Labels: cla: yes, status: in-progress

#1656 Update the server config to include the service account key scanner.
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
Labels: cla: yes, status: in-progress

#1649 Notifier error handling
  google/cloud/forseti/notifier/notifier.py
  tests/notifier/notifier_test.py
Labels: cla: yes, status: in-progress

#1653 Add inventory resources
  _faq/resource/resources.md
  _includes/docs/latest/resource_coverage.md
Labels: cla: yes, status: in-progress

#1659 Fix doc build
  travis/jekyll_build.sh
Labels: cla: yes

#1660 updated broken urls
  README.md
  _docs/_latest/configure/forseti/index.md
  _docs/_latest/configure/notifier/index.md
  _docs/_latest/configure/scanner/descriptions.md
  _docs/_latest/configure/scanner/rules.md
  _docs/_latest/develop/branch-methodology.md
  _docs/_latest/develop/rules_engine.md
  _docs/v1.1/howto/deploy/gcp-deployment.md
  _docs/v1.1/quickstarts/scanner/descriptions.md
  _docs/v1.1/quickstarts/scanner/rules.md
  _docs/v1.1/quickstarts/scanner/rules_engine.md
  _faq/using_forseti/scan-frequency.md
  _includes/docs/latest/min_conf_settings.md
  travis/jekyll_build.sh
Labels: cla: yes

#1642 setup updates
  _docs/_latest/setup/install.md
Labels: cla: yes, status: in-progress

#1652 Full review and update on Use section
  _docs/_latest/use/cli.md
  _docs/_latest/use/config.md
  _docs/_latest/use/enforcer.md
  _docs/_latest/use/explain.md
  _docs/_latest/use/inventory.md
  _docs/_latest/use/model.md
  _docs/_latest/use/notifier.md
  _docs/_latest/use/scanner.md
  _docs/_latest/use/server.md
  _faq/using_forseti/logs.md
  _includes/docs/latest/get_help_bug.md
  _includes/docs/latest/get_help_question.md
Labels: cla: no, status: in-progress

#1620 Update Dev Environment Setup for 2.0
  _docs/_latest/develop/dev-setup.md
  _includes/docs/latest/deployment_prerequisites.md
  _includes/docs/latest/forseti-server-gcp-required-roles.md
  _includes/docs/latest/required_apis.md
  _includes/docs/latest/setup_cloudsql.md
Labels: cla: no, status: in-progress

#1664 Moved git fetch to a comment with explanation
  _docs/_latest/setup/install.md
Labels: cla: yes

#1645 Review and Update FAQs
  _faq/general/create-issue.md
  _faq/installation_and_deployment/change-setup.md
  _faq/installation_and_deployment/separate-project.md
  _faq/installation_and_deployment/update-forseti.md
  _faq/installation_and_deployment/which-deployment.md
  _faq/resource/scanners.md
  _faq/security_implications/so-many-roles.md
  _faq/using_forseti/logs.md
  _faq/using_forseti/scan-frequency.md
Labels: cla: no, status: in-progress

#1658 2.0 forsetisecurity.org dev preseeded news articles
  _news/2018-03-28-published-gcp-podcast.md
  _news/2018-03-29-published-gcp-seurity-best-practices.md
  _news/2018-05-09-test-post.md
  _news/2018-05-24-forseti-hackday.md
  _news/2018-06-11-forseti-2.0-launch.md
Labels: cla: no, status: in-progress

#1667 Update change-setup.md
  _faq/installation_and_deployment/change-setup.md
Labels: cla: yes, status: in-progress

#1668 Standardize our bash codeblocks
  _docs/_latest/develop/dev-setup.md
  _docs/_latest/use/config.md
  _docs/_latest/use/enforcer.md
  _docs/_latest/use/explain.md
  _docs/_latest/use/inventory.md
  _docs/_latest/use/model.md
  _docs/_latest/use/notifier.md
  _docs/_latest/use/scanner.md
  _docs/_latest/use/server.md
  _includes/docs/latest/deployment_prerequisites.md
  _includes/docs/latest/setup_cloudsql.md
Labels: cla: yes, status: in-progress

#1669 News order reversal
  _config.yml
  news/index.html
Labels: cla: yes, status: in-progress

#1632 FAQ: How to install and run Forseti without Org Access.
  _faq/installation_and_deployment/run-forseti-without-org-access.md
Labels: cla: yes, release-testing: 2.0 RC3, status: in-progress

#1618 Manual installation guide
  _docs/_latest/develop/branch-methodology.md
  _docs/_latest/develop/dev-setup.md
  _docs/_latest/develop/inventory-new-data.md
  _docs/_latest/develop/rules_engine.md
  _docs/_latest/develop/testing.md
  _docs/_latest/setup/index.md
  _docs/_latest/setup/manual-deployment.md
  _includes/docs/latest/forseti-server-gcp-required-roles.md
  _includes/docs/latest/required_apis.md
Labels: cla: yes, release-testing: 2.0 RC3, status: in-progress

#1686 Added scanner config
  _docs/_latest/configure/scanner/descriptions.md
  _docs/_latest/configure/scanner/index.md
Labels: cla: yes, status: in-progress

#1689 Update installation instructions with urls to the updated website
  install/gcp/installer/util/constants.py
Labels: cla: yes, status: in-progress

#1695 Update cloudsql naming in rule file.
  rules/cloudsql_rules.yaml
Labels: cla: yes, status: in-progress

#1688 Added location check for KE pipeline
  google/cloud/security/common/gcp_api/_base_repository.py
  google/cloud/security/common/gcp_api/_supported_apis.py
  google/cloud/security/common/gcp_api/admin_directory.py
  google/cloud/security/common/gcp_api/appengine.py
  google/cloud/security/common/gcp_api/bigquery.py
  google/cloud/security/common/gcp_api/cloud_resource_manager.py
  google/cloud/security/common/gcp_api/cloudbilling.py
  google/cloud/security/common/gcp_api/cloudsql.py
  google/cloud/security/common/gcp_api/compute.py
  google/cloud/security/common/gcp_api/container.py
  google/cloud/security/common/gcp_api/iam.py
  google/cloud/security/common/gcp_api/storage.py
  google/cloud/security/common/gcp_type/bigquery_access_controls.py
  google/cloud/security/enforcer/gce_firewall_enforcer.py
  google/cloud/security/inventory/pipelines/load_ke_pipeline.py
  scripts/docker/base
  setup.py
  tests/common/gcp_api/container_test.py
  tests/common/gcp_api/test_data/fake_container_responses.py
Labels: cla: yes, status: in-progress

#1701 Update how to get new inventory data in 2.0
  _docs/_latest/develop/dev/inventory.md
Labels: cla: yes, status: in-progress

#1697 Update docs with new branches
  _docs/_latest/develop/branch-management.md
Labels: cla: no, status: in-progress

#1709 Website build improvements
  scripts/docker/data/conf.py
  scripts/docker/generate_sphinx_docs.Dockerfile
  scripts/generate_sphinx_docs.sh
  travis/jekyll_build.sh
Labels: cla: yes, status: in-progress

#1708 Update code links to use generated and versioned pydocs
  _docs/_latest/configure/notifier/index.md
  _docs/_latest/develop/dev/inventory.md
Labels: cla: yes, status: in-progress

#1714 Updated installation output
  install/gcp/installer/forseti_installer.py
Labels: cla: yes, status: in-progress

#1718 Fix scanner_iter() db session out of sync when used by multiple simultaneous queries.
  google/cloud/forseti/scanner/scanners/ke_version_scanner.py
  google/cloud/forseti/services/dao.py
Labels: cla: yes, status: in-progress

#1720 Remove additional db query from BigQuery scanner which conflicts with existing db session.
  google/cloud/forseti/scanner/scanners/bigquery_scanner.py
Labels: cla: no, status: in-progress

#1721 Fix blacklist scanner to handle network intefaces that do not have external internet access.
  google/cloud/forseti/scanner/audit/blacklist_rules_engine.py
Labels: cla: yes, status: in-progress

#1717 Handle the deprecated port field in backend service.
  google/cloud/forseti/scanner/scanners/iap_scanner.py
Labels: cla: yes, release-testing: 2.0 RC3, status: in-progress

#1725 faq updates, added more details to "Why run Forseti in its own separate project?"
  _faq/installation_and_deployment/separate-project.md
Labels: cla: yes, status: in-progress

#1726 Merge RC3 into Dev
  google/cloud/forseti/scanner/scanners/bigquery_scanner.py
  google/cloud/forseti/scanner/scanners/ke_version_scanner.py
  google/cloud/forseti/services/dao.py
Labels: cla: yes, status: in-progress

#1727 Merge Dev into 2.0.0 release branch
  README.md
  google/cloud/forseti/scanner/audit/blacklist_rules_engine.py
  google/cloud/forseti/scanner/scanners/bigquery_scanner.py
  google/cloud/forseti/scanner/scanners/iap_scanner.py
  google/cloud/forseti/scanner/scanners/ke_version_scanner.py
  google/cloud/forseti/services/dao.py
  install/gcp/installer/forseti_installer.py
Labels: cla: yes, status: in-progress

#1707 Doc for how to create a new GCP API client.
  _docs/_latest/develop/dev/gcp-api.md
  _docs/_latest/develop/dev/index.md
  _docs/_latest/develop/dev/scanner.md
  _docs/_latest/develop/dev/testing.md
Labels: cla: no, release-testing: 2.0 RC3, status: in-progress

#1728 FAQ for why number of projects are different with CSCC.
  _faq/resource/project-difference.md
Labels: cla: yes

#1729 Update project-difference.md
  _faq/resource/project-difference.md
Labels: cla: yes, release-testing: 2.0 RC3, status: in-progress

#1732 Merge 2.0 release branch into stable branch.
  README.md
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/common/gcp_type/resource.py
  google/cloud/forseti/scanner/audit/bigquery_rules_engine.py
  google/cloud/forseti/scanner/audit/blacklist_rules_engine.py
  google/cloud/forseti/scanner/audit/buckets_rules_engine.py
  google/cloud/forseti/scanner/audit/cloudsql_rules_engine.py
  google/cloud/forseti/scanner/audit/firewall_rules_engine.py
  google/cloud/forseti/scanner/audit/instance_network_interface_rules_engine.py
  google/cloud/forseti/scanner/scanners/bigquery_scanner.py
  google/cloud/forseti/scanner/scanners/iap_scanner.py
  google/cloud/forseti/scanner/scanners/ke_version_scanner.py
  google/cloud/forseti/services/dao.py
  google/cloud/forseti/services/inventory/base/resources.py
  install/gcp/installer/forseti_installer.py
  install/gcp/installer/util/constants.py
  install/gcp/installer/util/utils.py
  rules/cloudsql_rules.yaml
  tests/common/gcp_type/resource_test.py
  tests/scanner/audit/firewall_rules_engine_test.py
  tests/scanner/audit/iap_rules_engine_test.py
  tests/scanner/scanners/firewall_rules_scanner_test.py
  tests/scanner/scanners/ke_version_scanner_test.py
  tests/scanner/test_data/fake_bigquery_scanner_data.py
Labels: cla: yes, status: in-progress

#1734 fix sync script
  scripts/sync_latest_version.sh
Labels: cla: yes, status: in-progress

#1737 Revert .gitignore additions
  .gitignore
Labels: cla: yes, status: in-progress

#1738 Fix broken links
  _docs/_latest/setup/manual.md
Labels: cla: yes, status: in-progress

#1741 Update .gitignore
  .gitignore
Labels: cla: yes, status: in-progress

#1706 Added Service Account support for installing Forseti
  install/gcp/gcp_installer.py
  install/gcp/installer/configs/config.py
  install/gcp/installer/forseti_installer.py
  install/gcp/installer/util/gcloud.py
Labels: cla: yes, status: in-progress

#1681 Add Log Sinks (Exports) to the Forseti Inventory
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/common/gcp_api/_supported_apis.py
  google/cloud/forseti/common/gcp_api/stackdriver_logging.py
  google/cloud/forseti/services/inventory/base/gcp.py
  google/cloud/forseti/services/inventory/base/resources.py
  google/cloud/forseti/services/model/importer/importer.py
  tests/common/gcp_api/stackdriver_logging_test.py
  tests/common/gcp_api/test_data/fake_stackdriver_logging_responses.py
  tests/services/inventory/crawling_test.py
  tests/services/inventory/gcp_api_mocks.py
  tests/services/inventory/test_data/mock_gcp_results.py
  tests/services/model/importer/test_data/forseti-test.db
Labels: cla: yes, status: in-progress

#1750 Get Travis back to Green after merging the initial CSCC API PR
  google/cloud/forseti/common/gcp_api/_base_repository.py
  google/cloud/forseti/common/gcp_api/repository_mixins.py
  google/cloud/forseti/common/gcp_api/securitycenter.py
  google/cloud/forseti/notifier/notifiers/cscc_notifier.py
  tests/notifier/notifiers/cscc_notifier_test.py
Labels: cla: yes, status: in-progress

#1749 Fixing exemption typo issue#1643
  rules/audit_logging_rules.yaml
Labels: cla: yes, status: in-progress
