Repository forseti-security/forseti-security, pull requests merged in 2018-05, with the labels that each got.

#1480 Installer updates (Remove requirement for exporting service account for DWD)
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  deployment-templates/compute-engine/server/forseti-instance-server.py
  deployment-templates/deploy-forseti-server.yaml.in
  deployment-templates/deploy-forseti-server.yaml.sample
  google/cloud/forseti/services/inventory/crawler.py
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/server.py
  setup/gcp/installer/forseti_server_installer.py
  setup/gcp/installer/util/constants.py
  setup/gcp/installer/util/gcloud.py
  setup/gcp/run_forseti_installer.py
  setup/gcp/scripts/initialize_forseti_services.sh
  tests/gcp/installer/util/test_data/expected_merged_forseti_conf_server_from_1.1.10.yaml
  tests/gcp/installer/util/test_data/expected_merged_forseti_conf_server_from_1.1.6.yaml
  tests/gcp/installer/util/test_data/expected_merged_forseti_conf_server_from_1.1.9.yaml
  tests/gcp/installer/util/test_data/merge_to_forseti_conf_server.yaml
  tests/services/util/mock.py
Labels: cla: yes, status: in-progress

#1413 Documentation for Branch Methodology
  _docs/_latest/develop/branch-methodology.md
Labels: cla: no, status: in-progress

#1454 Add a scanner for Cloud Audit Logging configs
  configs/server/forseti_conf_server.yaml.in
  google/cloud/forseti/common/data_access/violation_map.py
  google/cloud/forseti/common/gcp_type/errors.py
  google/cloud/forseti/common/gcp_type/iam_policy.py
  google/cloud/forseti/scanner/audit/audit_logging_rules_engine.py
  google/cloud/forseti/scanner/scanner_requirements_map.py
  google/cloud/forseti/scanner/scanners/audit_logging_scanner.py
  rules/audit_logging_rules.yaml
  tests/common/gcp_type/iam_policy_test.py
  tests/scanner/audit/audit_logging_rules_engine_test.py
  tests/scanner/audit/data/audit_logging_test_invalid_rules.yaml
  tests/scanner/audit/data/audit_logging_test_valid_rules.yaml
  tests/scanner/scanners/audit_logging_scanner_test.py
  tests/scanner/test_data/fake_audit_logging_scanner_data.py
  tests/services/inventory/test_data/mock_gcp_results.py
  tests/services/model/importer/test_data/forseti-test.db
  tests/services/model/importer/update_test_dbs.py
Labels: cla: yes, status: in-progress

#1391 Documentation for Notifier
  _docs/_latest/configure/notifier/index.md
  _docs/_latest/use/cli.md
  _docs/_latest/use/notifier.md
Labels: cla: yes, status: in-progress

#1485 Updated gce host and docker to use ubuntu image version 18.04, added google cloud sdk installation in the startup script
  deployment-templates/compute-engine/server/forseti-instance-server.py
  deployment-templates/deploy-forseti-client.yaml.in
  deployment-templates/deploy-forseti-client.yaml.sample
  deployment-templates/deploy-forseti-server.yaml.in
  deployment-templates/deploy-forseti-server.yaml.sample
  setup/docker/base
Labels: cla: yes

#1486 Added createdAt field in the model response protos to expose the created at datetime
  google/cloud/forseti/services/model/model.proto
  google/cloud/forseti/services/model/service.py
Labels: cla: yes

#1491 Make Inventory Summary Query on "resource" Category
  google/cloud/forseti/services/inventory/storage.py
  tests/services/inventory/storage_test.py
Labels: cla: yes

#1492 Cherrypick Inventory Summary Fix into RC2
  google/cloud/forseti/services/inventory/storage.py
  tests/services/inventory/storage_test.py
Labels: cla: yes, status: in-progress

#1488 Prevent cron job to run if the previous job is not yet finished.
  deployment-templates/compute-engine/server/forseti-instance-server.py
Labels: cla: yes

#1496 Patch retention_days to RC2
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/inventory/inventory.proto
  google/cloud/forseti/services/inventory/inventory.py
  google/cloud/forseti/services/inventory/service.py
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/server.py
  setup/gcp/scripts/run_forseti.sh
  tests/services/api_tests/inventory_test.py
  tests/services/inventory/crawling_test.py
  tests/services/inventory/purge_inventory_test.py
Labels: cla: yes, status: in-progress

#1497 Terminate the installation if the deployment process failed.
  setup/gcp/installer/util/constants.py
  setup/gcp/installer/util/gcloud.py
Labels: cla: yes, status: in-progress

#1499 Updated argparse explanation for explainer list_resources
  google/cloud/forseti/services/cli.py
Labels: cla: yes, status: in-progress

#1426 Warn & prompt user if the authed user is different from the installation domain.
  setup/gcp/installer/forseti_installer.py
  setup/gcp/installer/util/constants.py
Labels: cla: yes, status: in-progress

#1409 Generate sphinx docs with Docker
  .travis.yml
  _config.yml
  _includes/site/layout/base/scripts.html
  _includes/site/layout/docs/category_nav.html
  _includes/site/layout/docs/tabs.html
  _sass/apidocs/_base.scss
  _sass/apidocs/_genindex.scss
  _sass/apidocs/_page.scss
  css/all.scss
  scripts/docker/data/conf.py
  scripts/docker/data/defindex.html
  scripts/docker/data/domainindex.html
  scripts/docker/data/genindex.html
  scripts/docker/data/index.rst
  scripts/docker/data/layout.html
  scripts/docker/data/page.html
  scripts/docker/generate_sphinx_docs.Dockerfile
  scripts/generate_sphinx_docs.sh
  third_party/sphinx-doc/AUTHORS
  third_party/sphinx-doc/LICENSE
  third_party/sphinx-doc/README
  travis/jekyll_build.sh
Labels: cla: yes, status: in-progress

#1508 Added edge case check when there is no rule defined in forwarding rule.
  google/cloud/forseti/scanner/audit/forwarding_rule_rules_engine.py
Labels: cla: yes, status: in-progress

#1510 Add News collection and pages
  Gemfile
  _config.yml
  _includes/site/layout/base/nav.html
  _includes/site/news/news_item.html
  _layouts/news.html
  _news/2018-05-09-test-post.md
  _sass/layouts/_news.scss
  css/all.scss
  news/index.html
Labels: cla: yes

#1512 2.0 inventory indexes
  google/cloud/forseti/services/inventory/storage.py
  tests/services/model/importer/test_data/forseti-test.db
Labels: cla: yes, status: in-progress

#1515 Open certain links in new windows
  _docs/_latest/configure/gsuite-group-collection.md
  _docs/v1.1/howto/configure/gsuite-group-collection.md
Labels: cla: yes, status: in-progress

#1513 Cleanup style and brokenness
  _docs/_latest/concepts/forseti-service-accounts.md
  _docs/_latest/concepts/index.md
  _docs/_latest/configure/email-notification.md
  _docs/_latest/configure/enforcer/index.md
  _docs/_latest/configure/explain/index.md
  _docs/_latest/configure/export-summary-notifications.md
  _docs/_latest/configure/gsuite-group-collection.md
  _docs/_latest/configure/index.md
  _docs/_latest/configure/inventory/index.md
  _docs/_latest/configure/scanner/index.md
  _docs/_latest/configure/scanner/rules.md
  _docs/_latest/develop/index.md
  _docs/_latest/develop/inventory-new-data.md
  _docs/_latest/faq/index.md
  _docs/_latest/quickstarts/explain.md
  _docs/_latest/setup/index.md
  _docs/_latest/setup/install.md
  _docs/_latest/use/cli.md
  _docs/_latest/use/enforcer.md
  _docs/_latest/use/index.md
  _docs/_latest/use/inventory.md
  _docs/_latest/use/notifier.md
Labels: cla: yes

#1516 Remove confusing link in gsuite enablement.
  _docs/_latest/configure/gsuite-group-collection.md
  _docs/v1.1/howto/configure/gsuite-group-collection.md
Labels: cla: yes

#1503 Documentation for Data Models
  _docs/_latest/concepts/models.md
Labels: cla: yes, status: in-progress

#1504 Documentation for CLI
  _docs/_latest/use/cli.md
  _docs/_latest/use/notifier.md
Labels: cla: yes, status: in-progress

#1520 Update docker_setup_forseti.sh
  setup/scripts/docker_setup_forseti.sh
Labels: cla: yes

#1523 Add logging for model creation.
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/model/modeller.py
  google/cloud/forseti/services/model/service.py
Labels: cla: yes

#1518 Updated BufferedDbWriter add() method do proper length comparison
  google/cloud/forseti/services/inventory/crawler.py
  google/cloud/forseti/services/inventory/storage.py
  tests/services/inventory/storage_test.py
Labels: cla: yes

#1521 Fix the forsetisecurity.org build
  .gitignore
  _docs/_latest/configure/scanner/index.md
  _news/2018-05-09-test-post.md
  scripts/generate_sphinx_docs.sh
  travis/jekyll_build.sh
Labels: cla: yes

#1494 Setup dedicated Forseti log to fix newlines being cut off on Stackdriver
  configs/logging/fluentd/forseti.conf
  configs/logging/logrotate/forseti
  deployment-templates/compute-engine/server/forseti-instance-server.py
  google/cloud/forseti/common/util/logger.py
Labels: cla: yes, status: in-progress

#1514 Added server_config service and cli
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/server.py
  google/cloud/forseti/services/server_config/.grpc_service
  google/cloud/forseti/services/server_config/__init__.py
  google/cloud/forseti/services/server_config/server.proto
  google/cloud/forseti/services/server_config/service.py
  setup/gcp/scripts/run_forseti.sh
  tests/services/api_tests/inventory_test.py
  tests/services/inventory/crawling_test.py
  tests/services/server_test.py
  tests/services/test_data/forseti_conf_server.yaml
  tests/services/test_data/forseti_conf_server_new.yaml
Labels: cla: yes, status: in-progress

#1528 Make the forseti.log writeable when user tries to use the client in the server VM.
  deployment-templates/compute-engine/server/forseti-instance-server.py
  google/cloud/forseti/common/util/logger.py
Labels: cla: yes, status: in-progress

#1532 Merge rc2 into dev
  google/cloud/forseti/services/model/importer/importer.py
  tests/notifier/notifier_test.py
  tests/services/inventory/test_data/mock_gcp_results.py
  tests/services/model/importer/importer_test.py
  tests/services/model/importer/test_data/forseti-test.db
  tests/services/model/importer/update_test_dbs.py
Labels: cla: yes

#1531 Added /develop/reference as part of files to ignore
  travis/jekyll_build.sh
Labels: cla: yes

#1534 Improve the formatting of the best practices page
  _docs/_latest/concepts/best-practices.md
Labels: cla: yes, status: in-progress

#1348 Architecture update
  _docs/_latest/concepts/architecture.md
  images/docs/concepts/forseti-architecture.png
Labels: cla: yes, status: in-progress

#1401 Moved quickstart/explain/index to user/explain
  _docs/_latest/quickstarts/explain.md
  _docs/_latest/setup/index.md
  _docs/_latest/use/explain.md
Labels: cla: yes, status: in-progress

#1232 2.0 quickstarts/scanner/*
  _docs/_latest/configure/explain/index.md
  _docs/_latest/configure/index.md
  _docs/_latest/configure/scanner/default_rules.md
  _docs/_latest/configure/scanner/descriptions.md
  _docs/_latest/configure/scanner/index.md
  _docs/_latest/configure/scanner/policy-violations.md
  _docs/_latest/configure/scanner/rule_engine.md
  _docs/_latest/configure/scanner/rules.md
  _docs/_latest/setup/index.md
  about/index.md
Labels: cla: yes, status: in-progress

#1542 Add lightbox to all responsive images
  .gitignore
  _includes/responsive_image/template.html
  _includes/site/layout/base/scripts.html
  _includes/site/layout/base/stylesheets.html
  third_party/lightbox/.editorconfig
  third_party/lightbox/.github/ISSUE_TEMPLATE.md
  third_party/lightbox/.github/PULL_REQUEST_TEMPLATE.md
  third_party/lightbox/.gitignore
  third_party/lightbox/.jscsrc
  third_party/lightbox/.jshintrc
  third_party/lightbox/DEPLOY.md
  third_party/lightbox/Gruntfile.js
  third_party/lightbox/LICENSE
  third_party/lightbox/README.md
  third_party/lightbox/ROADMAP.md
  third_party/lightbox/bower.json
  third_party/lightbox/dist/css/lightbox.css
  third_party/lightbox/dist/css/lightbox.min.css
  third_party/lightbox/dist/images/close.png
  third_party/lightbox/dist/images/loading.gif
  third_party/lightbox/dist/images/next.png
  third_party/lightbox/dist/images/prev.png
  third_party/lightbox/dist/js/lightbox-plus-jquery.js
  third_party/lightbox/dist/js/lightbox-plus-jquery.min.js
  third_party/lightbox/dist/js/lightbox-plus-jquery.min.map
  third_party/lightbox/dist/js/lightbox.js
  third_party/lightbox/dist/js/lightbox.min.js
  third_party/lightbox/dist/js/lightbox.min.map
  third_party/lightbox/package.json
  third_party/lightbox/src/css/lightbox.css
  third_party/lightbox/src/images/close.png
  third_party/lightbox/src/images/loading.gif
  third_party/lightbox/src/images/next.png
  third_party/lightbox/src/images/prev.png
  third_party/lightbox/src/js/lightbox.js
Labels: cla: yes

#1544 Reduce header sizing and give more space to docs
  _layouts/docs.html
  _sass/base/_typography.scss
Labels: cla: yes

#1546 Add support for zippies in docs
  _includes/site/layout/base/scripts.html
  _includes/site/zippy/item.html
Labels: cla: yes

#1541 Ignore generated docs.
  .gitignore
Labels: cla: yes

#1540 Fix images to use the responsive tag
  _docs/_latest/concepts/architecture.md
Labels: cla: yes

#1551 Rename setup directory to install.
  .gitignore
  .travis.yml
  deployment-templates/compute-engine/server/forseti-instance-server.py
  install/__init__.py
  install/dependencies/apt_packages.txt
  install/docker/base
  install/docker/cloudbuild.yaml
  install/docker/forseti
  install/gcp/__init__.py
  install/gcp/gcp_installer.py
  install/gcp/installer/__init__.py
  install/gcp/installer/configs/__init__.py
  install/gcp/installer/configs/client_config.py
  install/gcp/installer/configs/config.py
  install/gcp/installer/configs/server_config.py
  install/gcp/installer/forseti_client_installer.py
  install/gcp/installer/forseti_installer.py
  install/gcp/installer/forseti_server_installer.py
  install/gcp/installer/util/__init__.py
  install/gcp/installer/util/constants.py
  install/gcp/installer/util/files.py
  install/gcp/installer/util/gcloud.py
  install/gcp/installer/util/merge_engine.py
  install/gcp/installer/util/upgradeable_resources.py
  install/gcp/installer/util/utils.py
  install/gcp/scripts/initialize_forseti_services.sh
  install/gcp/scripts/run_forseti.sh
  install/gcp/util/__init__.py
  install/gcp/util/rotate_gsuite_key.py
  install/gcp_installer.py
  install/scripts/docker_install_forseti.sh
  install/scripts/docker_pylint_forseti.sh
  install/scripts/docker_setup_forseti.sh
  install/scripts/docker_unittest_forseti.sh
  install/util/__init__.py
  install/util/build_protos.py
  setup.py
  tests/gcp/installer/util/files_test.py
  tests/gcp/installer/util/functional_test.py
  tests/gcp/installer/util/gcloud_test.py
  tests/gcp/installer/util/merge_engine_test.py
  tests/gcp/installer/util/utils_test.py
Labels: cla: yes

#1545 Updated to use compute engine library's ping method to check if metadata server is available
  google/cloud/forseti/common/util/metadata_server.py
  tests/common/util/metadata_server_test.py
Labels: cla: yes

#1526 2.0 inventory db cleanup
  google/cloud/forseti/common/util/date_time.py
  google/cloud/forseti/notifier/notifiers/email_violations.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/inventory/base/resources.py
  google/cloud/forseti/services/inventory/inventory.proto
  google/cloud/forseti/services/inventory/inventory.py
  google/cloud/forseti/services/inventory/service.py
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/model/service.py
  google/cloud/forseti/services/scanner/dao.py
  setup.py
  tests/common/util/date_time_test.py
  tests/notifier/notifiers/email_violations_test.py
  tests/scanner/scanner_test.py
  tests/services/inventory/storage_test.py
  tests/services/model/importer/importer_test.py
  tests/services/model/importer/test_data/forseti-test.db
  tests/services/model/importer/update_test_dbs.py
  tests/services/scanner/scanner_dao_test.py
Labels: cla: yes, priority: p1, release-testing: 2.0 RC2, status: in-progress, triaged: yes

#1556 Enabled upload inventory summary to gcs bucket by default
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  deployment-templates/deploy-forseti-client.yaml.in
  deployment-templates/deploy-forseti-client.yaml.sample
  deployment-templates/deploy-forseti-server.yaml.in
  deployment-templates/deploy-forseti-server.yaml.sample
  install/gcp/installer/forseti_client_installer.py
  install/gcp/installer/forseti_server_installer.py
Labels: cla: yes

#1558 Fix the CSV header not breaking correctly across columns
  google/cloud/forseti/common/data_access/csv_writer.py
  tests/notifier/notifiers/test_data/expected_attachment.csv
Labels: cla: yes

#1561 clean up the code to change inventory_index_id arg to type int64 everywhere except at the parser level
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/notifier/notifiers/base_notification.py
  google/cloud/forseti/notifier/notifiers/cscc_notifier.py
  google/cloud/forseti/notifier/notifiers/email_violations.py
  google/cloud/forseti/notifier/notifiers/inventory_summary.py
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/inventory/inventory.py
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/model/model.proto
  google/cloud/forseti/services/model/modeller.py
  google/cloud/forseti/services/notifier/notifier.proto
  google/cloud/forseti/services/notifier/service.py
  tests/notifier/notifiers/email_violations_test.py
  tests/notifier/notifiers/gcs_violations_test.py
  tests/services/cli_test.py
Labels: cla: yes

#1562 cli better grpc error handling
  google/cloud/forseti/services/cli.py
  tests/services/cli_test.py
Labels: cla: yes

#1564 Fix Missing Scopes in Local Environment
  google/cloud/forseti/common/gcp_api/api_helpers.py
  tests/common/gcp_api/api_helpers_test.py
Labels: cla: yes

#1579 Update docs README with documentation for all new functionality
  README.md
  images/readme/docs_api_doc_page.jpg
  images/readme/docs_api_index.jpg
  images/readme/docs_api_module_index.jpg
  images/readme/docs_api_source_page.jpg
  images/readme/docs_opened_responsive_image.jpg
  images/readme/docs_unopened_responsive_image.jpg
  images/readme/docs_version_dropdown.jpg
  images/readme/docs_zippy_closed.jpg
  images/readme/docs_zippy_open.jpg
Labels: cla: yes

#1581 Document release process for versioning
  README.md
Labels: cla: yes

#1555 Updated service account image
  images/docs/concepts/service-account-architecture.png
Labels: cla: yes

#1583 Fix border popping on category navigation
  _sass/base/_override.scss
Labels: cla: yes

#1580 Fix sphinx docgen and latest version sync script
  scripts/generate_sphinx_docs.sh
  scripts/sync_latest_version.sh
Labels: cla: yes

#1584 CLI stacktrace clean up
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/client.py
Labels: cla: yes

#1588 Updated firewall rule to not call the parse function when the time is empty
  google/cloud/forseti/common/gcp_type/firewall_rule.py
Labels: cla: yes

#1589 Handle error from saving cscc findings.
  google/cloud/forseti/notifier/notifiers/cscc_notifier.py
Labels: cla: yes

#1592 Clarify required flags
  google/cloud/forseti/services/cli.py
  tests/services/cli_test.py
Labels: cla: yes

#1594 Updated kubernetes violation to use full name instead of parent full name
  google/cloud/forseti/scanner/audit/ke_version_rules_engine.py
  google/cloud/forseti/scanner/scanners/ke_version_scanner.py
  tests/scanner/scanners/ke_version_scanner_test.py
Labels: cla: yes, status: in-progress

#1596 Removed google.apputils usage in stubs
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/stubs.py
Labels: cla: yes, status: in-progress

#1597 Updated lock file location
  deployment-templates/compute-engine/server/forseti-instance-server.py
  forseti_cron_runner.lock
Labels: cla: yes, status: in-progress

#1602 Update flags to use store_true instead of taking in boolean value
  google/cloud/forseti/services/cli.py
  tests/services/cli_test.py
Labels: cla: yes

#1604 Update ke scanner rule to address security bulletin
  rules/ke_rules.yaml
Labels: cla: yes

#1582 Updated explain doc
  _docs/_latest/use/explain.md
Labels: cla: yes

#1607 Added cloud function script to export inventory summary to bigquery
  scripts/inventory/export_inventory_summary_to_bigquery.js
Labels: cla: yes, status: in-progress

#1598 Port Inventory email to 2.0
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/common/email_templates/inventory_summary.jinja
  google/cloud/forseti/common/util/errors.py
  google/cloud/forseti/common/util/string_formats.py
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/notifier/notifiers/inventory_summary.py
  tests/notifier/notifier_test.py
  tests/notifier/notifiers/inventory_summary_test.py
Labels: cla: yes, status: in-progress

#1608 Remove default plain text output style
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/inventory/service.py
  tests/services/cli_test.py
Labels: cla: yes

#1615 Increased column size for inventory errors and message
  google/cloud/forseti/services/dao.py
  google/cloud/forseti/services/inventory/storage.py
Labels: cla: yes

#1610 Concepts review
  _docs/_latest/concepts/architecture.md
  _docs/_latest/concepts/best-practices.md
  _docs/_latest/concepts/default-rules.md
  _docs/_latest/concepts/forseti-service-accounts.md
  _docs/_latest/concepts/index.md
  _docs/_latest/concepts/models.md
  _docs/_latest/concepts/service-accounts.md
  _docs/_latest/configure/index.md
  _docs/_latest/configure/scanner/policy-violations.md
  _docs/_latest/develop/index.md
  _docs/_latest/faq/index.md
  _docs/_latest/index.md
  _docs/_latest/setup/index.md
  _docs/_latest/setup/upgrade.md
  _docs/_latest/use/index.md
  _faq/installation_and_deployment/org-data-access.md
  _faq/security_implications/gsuite-key.md
  _faq/security_implications/read-data.md
  _faq/security_implications/so-many-roles.md
  _includes/docs/latest/deployment_prerequisites.md
  _includes/docs/latest/forseti-client-gcp-required-roles.md
  _includes/docs/latest/forseti-server-gcp-required-roles.md
  _includes/docs/latest/required_apis.md
  images/docs/concepts/service-account-architecture.png
Labels: cla: yes

#1617 Merge RC3 to 2.0-dev
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  deployment-templates/compute-engine/server/forseti-instance-server.py
  forseti_cron_runner.lock
  google/cloud/forseti/common/email_templates/inventory_summary.jinja
  google/cloud/forseti/common/gcp_api/api_helpers.py
  google/cloud/forseti/common/gcp_type/firewall_rule.py
  google/cloud/forseti/common/util/errors.py
  google/cloud/forseti/common/util/string_formats.py
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/notifier/notifiers/base_notification.py
  google/cloud/forseti/notifier/notifiers/cscc_notifier.py
  google/cloud/forseti/notifier/notifiers/email_violations.py
  google/cloud/forseti/notifier/notifiers/inventory_summary.py
  google/cloud/forseti/scanner/audit/ke_version_rules_engine.py
  google/cloud/forseti/scanner/scanners/ke_version_scanner.py
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/dao.py
  google/cloud/forseti/services/db.py
  google/cloud/forseti/services/inventory/inventory.py
  google/cloud/forseti/services/inventory/service.py
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/model/model.proto
  google/cloud/forseti/services/model/modeller.py
  google/cloud/forseti/services/notifier/notifier.proto
  google/cloud/forseti/services/notifier/service.py
  google/cloud/forseti/stubs.py
  install/gcp/gcp_installer.py
  install/gcp/installer/configs/config.py
  install/gcp/installer/configs/server_config.py
  install/gcp/installer/forseti_client_installer.py
  install/gcp/installer/forseti_installer.py
  install/gcp/installer/forseti_server_installer.py
  rules/ke_rules.yaml
  scripts/inventory/export_inventory_summary_to_bigquery.js
  tests/common/gcp_api/api_helpers_test.py
  tests/notifier/notifier_test.py
  tests/notifier/notifiers/email_violations_test.py
  tests/notifier/notifiers/gcs_violations_test.py
  tests/notifier/notifiers/inventory_summary_test.py
  tests/scanner/scanners/ke_version_scanner_test.py
  tests/services/cli_test.py
Labels: cla: yes, status: in-progress

#1619 Add "Get Help" page
  _docs/_latest/develop/get-help.md
  _docs/_latest/use/get-help.md
  _includes/docs/latest/get_help_bug.md
  _includes/docs/latest/get_help_question.md
  community/index.md
Labels: cla: yes

#1623 Removed enforcer configure, updated index.md in "use" to show enforcer link
  _docs/_latest/configure/enforcer/index.md
  _docs/_latest/configure/index.md
  _docs/_latest/use/index.md
  _faq/resource/enforcers.md
  about/index.md
Labels: cla: yes

#1624 Added parameter to skip SendGrid configuration
  install/gcp/gcp_installer.py
  install/gcp/installer/configs/server_config.py
  install/gcp/installer/forseti_server_installer.py
  install/gcp/installer/util/constants.py
Labels: cla: yes
