Repository forseti-security/forseti-security, pull requests merged in 2018-02, with the labels that each got.

#1058 Add ignore regexp and fix other broken bits.
  .travis.yml
  _docs/configure/explain/index.md
  _docs/configure/gsuite-group-collection.md
Labels: cla: yes, status: in-progress

#1063 Create the docs/use/ documentation path.
  _config.yml
  _data/doc_categories.yml
  _docs/index.md
  _docs/use/index.md
Labels: cla: yes, status: in-progress

#1061 Replace IAM Explain with just Explain
  _docs/concepts/forseti-service-accounts.md
  _docs/configure/explain/index.md
  _docs/setup/install-forseti-security.md
  about/index.md
Labels: cla: yes, status: in-progress

#1065 Clean up scanner, removed all the client config related args
  google/cloud/forseti/scanner/scanner.py
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/scanner/scanner.proto
  google/cloud/forseti/services/scanner/service.py
Labels: cla: yes, status: in-progress

#1067 Install Cloud SDK.
  scripts/docker/base
Labels: cla: yes

#1068 Hotfix: `gcloud alpha service-management` is deprecated and is now replaced with `gcloud services`
  scripts/gcp_setup/environment/gcloud_env.py
Labels: cla: yes, status: in-progress

#1062 Update references to IAM Explain
  google/cloud/forseti/services/explain/explainer.py
  google/cloud/forseti/services/explain/service.py
  setup/gcp/environment/gcloud_env.py
Labels: cla: yes, status: in-progress

#1064 Make the Notifier work with the new 2.0 Violations
  google/cloud/forseti/common/data_access/violation_dao.py
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/notifier/pipelines/email_violations_pipeline.py
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/notifier/notifier.proto
  google/cloud/forseti/services/notifier/service.py
  google/cloud/forseti/services/scanner/dao.py
  tests/common/data_access/test_data/fake_violation_dao_data.py
  tests/common/data_access/violation_dao_test.py
  tests/scanner/scanners/blacklist_scanner_test.py
  tests/services/cli_test.py
  tests/services/scanner/scanner_dao_test.py
Labels: cla: yes, status: in-progress

#1070 Use sort to get the last inventory index record.
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/services/inventory/storage.py
Labels: cla: yes, status: in-progress

#1050 Enable calling build_protos through setup.py
  setup.py
  setup/utils/build_protos.py
Labels: cla: yes, status: in-progress

#1047 Quiet the build even more
  .travis.yml
  setup/docker/base
  setup/docker/forseti
  setup/scripts/build_docker.sh
  setup/scripts/run_docker_tests.sh
Labels: cla: yes, status: in-progress

#1081 Fix the startup script after #1050.
  deployment-templates/compute-engine/forseti-instance.py
Labels: cla: yes, status: in-progress

#1079 Tweak the log format
  google/cloud/forseti/common/util/logger.py
Labels: cla: yes, status: in-progress

#1069 Install and expose glcoud on the docker testing image.
  setup/docker/base
  setup/docker/forseti
  setup/scripts/build_docker.sh
Labels: cla: yes, status: in-progress

#1089 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: cla: yes, status: in-progress

#1088 Improving setup
  deployment-templates/compute-engine/forseti-instance.py
  google/cloud/forseti/scanner/scanners/groups_scanner.py
  requirements.txt
  setup/dependencies/pip_packages.txt
  setup/docker/forseti
Labels: cla: yes, status: in-progress

#1092 Inventory column size increased
  google/cloud/forseti/services/inventory/storage.py
Labels: cla: yes, status: in-progress

#1045 Update inventory info model: Query inventory root_id and whether gsuite enabled. Then import to data model
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/model/importer/importer.py
  tests/services/model/importer/importer_test.py
Labels: cla: yes, status: in-progress

#1071 Update all scanners to output violations with inventory_index_id, full_name, inventory_data
  google/cloud/forseti/common/data_access/csv_writer.py
  google/cloud/forseti/common/gcp_type/backend_service.py
  google/cloud/forseti/common/gcp_type/bucket_access_controls.py
  google/cloud/forseti/common/gcp_type/cloudsql_access_controls.py
  google/cloud/forseti/common/gcp_type/folder.py
  google/cloud/forseti/common/gcp_type/forwarding_rule.py
  google/cloud/forseti/common/gcp_type/instance.py
  google/cloud/forseti/common/gcp_type/organization.py
  google/cloud/forseti/common/gcp_type/project.py
  google/cloud/forseti/scanner/audit/blacklist_rules_engine.py
  google/cloud/forseti/scanner/audit/buckets_rules_engine.py
  google/cloud/forseti/scanner/audit/cloudsql_rules_engine.py
  google/cloud/forseti/scanner/audit/firewall_rules_engine.py
  google/cloud/forseti/scanner/audit/forwarding_rule_rules_engine.py
  google/cloud/forseti/scanner/audit/iam_rules_engine.py
  google/cloud/forseti/scanner/audit/iap_rules_engine.py
  google/cloud/forseti/scanner/audit/instance_network_interface_rules_engine.py
  google/cloud/forseti/scanner/audit/ke_version_rules_engine.py
  google/cloud/forseti/scanner/audit/rules.py
  google/cloud/forseti/scanner/scanners/blacklist_scanner.py
  google/cloud/forseti/scanner/scanners/bucket_rules_scanner.py
  google/cloud/forseti/scanner/scanners/cloudsql_rules_scanner.py
  google/cloud/forseti/scanner/scanners/firewall_rules_scanner.py
  google/cloud/forseti/scanner/scanners/forwarding_rule_scanner.py
  google/cloud/forseti/scanner/scanners/groups_scanner.py
  google/cloud/forseti/scanner/scanners/iam_rules_scanner.py
  google/cloud/forseti/scanner/scanners/iap_scanner.py
  google/cloud/forseti/scanner/scanners/instance_network_interface_scanner.py
  google/cloud/forseti/scanner/scanners/ke_version_scanner.py
  tests/common/data_access/violation_dao_test.py
  tests/common/gcp_type/project_test.py
  tests/common/gcp_type/resource_test.py
  tests/notifier/pipelines/email_scanner_summary_pipeline_test.py
  tests/scanner/audit/buckets_rules_engine_test.py
  tests/scanner/audit/cloudsql_rules_engine_test.py
  tests/scanner/audit/firewall_rules_engine_test.py
  tests/scanner/audit/iam_rules_engine_test.py
  tests/scanner/audit/iap_rules_engine_test.py
  tests/scanner/iap_scanner_test.py
  tests/scanner/scanners/firewall_rules_scanner_test.py
  tests/scanner/scanners/forwarding_rule_rules_scanner_test.py
  tests/scanner/scanners/ke_version_scanner_test.py
  tests/scanner/test_data/fake_blacklist_scanner_data.py
Labels: cla: yes, status: in-progress

#1111 Reorder configure before using.
  _data/doc_categories.yml
  _docs/index.md
Labels: cla: yes, status: in-progress

#1113 Increase the size of column `data` in resource table
  google/cloud/forseti/services/dao.py
Labels: cla: yes, status: in-progress

#1094 Add libpython-dev apt package dependency
  setup/dependencies/apt_packages.txt
Labels: cla: yes, status: in-progress

#1093 Support iam policy member of domain type in iam scanner's required mode,
  google/cloud/security/common/gcp_type/iam_policy.py
  tests/common/gcp_type/iam_policy_test.py
  tests/scanner/audit/data/test_rules.py
  tests/scanner/audit/iam_rules_engine_test.py
Labels: cla: yes, status: in-progress

#1116 Increase role description column to 1024 szie
  google/cloud/forseti/services/dao.py
Labels: cla: yes, status: in-progress

#1102 Ensure full_name db key is unique by adding type_name into resource full_name
  google/cloud/forseti/services/model/importer/importer.py
Labels: cla: yes, status: in-progress

#1119 Make the inventory_data column size in violations table to be the same as from the resource model.
  google/cloud/forseti/services/scanner/dao.py
Labels: cla: yes, status: in-progress

#1099 Remove the 1.0 DAO
  google/cloud/forseti/common/data_access/_db_connector.py
  google/cloud/forseti/common/data_access/dao.py
  google/cloud/forseti/common/data_access/forseti.py
  google/cloud/forseti/common/data_access/load_data_sql_provider.py
  google/cloud/forseti/common/data_access/project_dao.py
  google/cloud/forseti/common/data_access/sql_queries/__init__.py
  google/cloud/forseti/common/data_access/sql_queries/create_tables.py
  google/cloud/forseti/common/data_access/sql_queries/load_data.py
  google/cloud/forseti/common/data_access/sql_queries/select_data.py
  google/cloud/forseti/common/data_access/sql_queries/snapshot_cycles_sql.py
  google/cloud/forseti/common/data_access/violation_dao.py
  google/cloud/forseti/common/data_access/violation_format.py
  google/cloud/forseti/common/util/parser.py
  google/cloud/forseti/notifier/pipelines/base_notification_pipeline.py
  google/cloud/forseti/scanner/scanner.py
  tests/common/data_access/__init__.py
  tests/common/data_access/csv_writer_test.py
  tests/common/data_access/dao_test.py
  tests/common/data_access/project_dao_test.py
  tests/common/data_access/test_data/__init__.py
  tests/common/data_access/test_data/fake_violation_dao_data.py
  tests/common/data_access/violation_dao_test.py
  tests/notifier/pipelines/base_notification_pipeline_test.py
  tests/scanner/scanner_test.py
  tests/services/scanner/scanner_dao_test.py
Labels: cla: yes, status: in-progress

#1128 Update appengine client to not log warnings for expected responses.
  google/cloud/forseti/common/gcp_api/appengine.py
  tests/common/gcp_api/appengine_test.py
  tests/common/gcp_api/test_data/fake_appengine_responses.py
Labels: cla: yes, status: in-progress

#1121 updated cloudsql_region in the server_config class to have default value
  setup/gcp/install_setup.py
  setup/gcp/installer/configs/config.py
  setup/gcp/installer/configs/server_config.py
Labels: cla: yes, status: in-progress

#1134 Updated run_forseti.sh
  setup/gcp/scripts/run_forseti.sh
Labels: cla: yes

#1133 Added firewall rule for forseti server to allow ssh connection.
  setup/gcp/installer/forseti_server_installer.py
Labels: cla: yes, status: in-progress

#1137 Using set -x to print commands used in the script.
  setup/gcp/scripts/run_forseti.sh
Labels: cla: yes, status: in-progress

#1123 port of PR #1093 to the 2.0-dev branch
  google/cloud/forseti/common/gcp_type/iam_policy.py
  tests/common/gcp_type/iam_policy_test.py
  tests/scanner/audit/data/test_rules.py
  tests/scanner/audit/iam_rules_engine_test.py
Labels: cla: yes, status: in-progress

#1129 Add configurable cleanup of inventory tables (#438)
  configs/forseti_conf.yaml.in
  configs/forseti_conf.yaml.sample
  google/cloud/security/common/data_access/forseti_system_dao.py
  google/cloud/security/common/data_access/sql_queries/cleanup_tables_sql.py
  google/cloud/security/inventory/inventory_loader.py
  tests/common/data_access/forseti_system_dao_test.py
Labels: cla: yes

#1140 Added wait time for enable_apis
  setup/gcp/installer/util/gcloud.py
  setup/gcp/installer/util/utils.py
  tests/gcp/installer/util/installer_gcloud_test.py
Labels: cla: yes, status: in-progress

#1142 Removed async while enabling API to guaranteed apis fully enabled.
  setup/gcp/installer/util/gcloud.py
Labels: cla: yes, status: in-progress

#1135 Update forseti server to pull most configuration from the server config.
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  deployment-templates/compute-engine/server/forseti-instance-server.py
  deployment-templates/deploy-forseti-server.yaml.in
  deployment-templates/deploy-forseti-server.yaml.sample
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/scanner/scanner.py
  google/cloud/forseti/services/inventory/crawler.py
  google/cloud/forseti/services/server.py
  setup/gcp/installer/forseti_server_installer.py
  setup/gcp/scripts/initialize_forseti_services.sh
  setup/gcp/scripts/run_forseti.sh
  tests/services/api_tests/inventory_test.py
  tests/services/inventory/crawling_test.py
Labels: cla: yes, status: in-progress

#1149 Model delete name
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  deployment-templates/compute-engine/server/forseti-instance-server.py
  deployment-templates/deploy-forseti-server.yaml.in
  deployment-templates/deploy-forseti-server.yaml.sample
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/scanner/scanner.py
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/inventory/crawler.py
  google/cloud/forseti/services/server.py
  setup/gcp/installer/forseti_server_installer.py
  setup/gcp/scripts/initialize_forseti_services.sh
  setup/gcp/scripts/run_forseti.sh
  tests/services/api_tests/inventory_test.py
  tests/services/cli_test.py
  tests/services/inventory/crawling_test.py
Labels: cla: yes, status: in-progress

#1138 Violation hashing
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/scanner/dao.py
  tests/services/scanner/scanner_dao_test.py
Labels: cla: yes, status: in-progress

#1152 The deployment timestamp should be consistent for both client and server.
  setup/gcp/install_setup.py
  setup/gcp/installer/configs/config.py
Labels: cla: yes, status: in-progress

#1156 Standardize on string quoting
  google/cloud/forseti/common/gcp_api/admin_directory.py
  google/cloud/forseti/common/gcp_api/appengine.py
  google/cloud/forseti/common/gcp_api/bigquery.py
  google/cloud/forseti/common/gcp_api/cloud_resource_manager.py
  google/cloud/forseti/common/gcp_api/cloudbilling.py
  google/cloud/forseti/common/gcp_api/cloudsql.py
  google/cloud/forseti/common/gcp_api/iam.py
  google/cloud/forseti/common/gcp_api/storage.py
  google/cloud/forseti/common/util/parser.py
  google/cloud/forseti/notifier/pipelines/email_violations_pipeline.py
  google/cloud/forseti/scanner/audit/blacklist_rules_engine.py
  google/cloud/forseti/scanner/scanners/blacklist_scanner.py
  google/cloud/forseti/scanner/scanners/firewall_rules_scanner.py
  google/cloud/forseti/scanner/scanners/instance_network_interface_scanner.py
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/dao.py
  google/cloud/forseti/services/explain/explainer.py
  google/cloud/forseti/services/explain/service.py
  google/cloud/forseti/services/inventory/inventory.py
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/model/modeller.py
  google/cloud/forseti/services/model/service.py
  google/cloud/forseti/services/notifier/service.py
  google/cloud/forseti/services/playground/playgrounder.py
  google/cloud/forseti/services/playground/service.py
  google/cloud/forseti/services/scanner/dao.py
  google/cloud/forseti/services/scanner/service.py
  google/cloud/forseti/services/server.py
  pylintrc
  setup.py
  setup/gcp/installer/util/gcloud.py
  setup/util/build_protos.py
Labels: cla: yes, status: in-progress

#1155 Rule files default values
  rules/bigquery_rules.yaml
  rules/bucket_rules.yaml
  rules/cloudsql_rules.yaml
  rules/firewall_rules.yaml
  rules/forwarding_rules.yaml
  rules/group_rules.yaml
  rules/iam_rules.yaml
  rules/iap_rules.yaml
  setup/gcp/installer/forseti_server_installer.py
  setup/gcp/installer/util/files.py
  setup/gcp/installer/util/gcloud.py
Labels: cla: yes, status: in-progress

#1159 members in bindings can have duplicates
  google/cloud/forseti/services/model/importer/importer.py
  tests/services/inventory/test_data/mock_gcp_results.py
  tests/services/model/importer/test_data/forseti-test.db
  tests/services/model/importer/update_test_dbs.py
Labels: cla: yes, status: in-progress

#1141 Storing timestamps for scanner violations
  google/cloud/forseti/services/scanner/dao.py
  tests/services/scanner/scanner_dao_test.py
Labels: cla: yes, status: in-progress

#1146 Delete data model after each cron run
  google/cloud/forseti/services/cli.py
  setup/gcp/scripts/run_forseti.sh
  tests/services/cli_test.py
Labels: cla: no, status: in-progress

#1053 Documentation in services including explain, inventory, model, playground
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/dao.py
  google/cloud/forseti/services/db.py
  google/cloud/forseti/services/explain/explainer.py
  google/cloud/forseti/services/explain/service.py
  google/cloud/forseti/services/inventory/base/gcp.py
  google/cloud/forseti/services/inventory/base/progress.py
  google/cloud/forseti/services/inventory/base/resources.py
  google/cloud/forseti/services/inventory/base/storage.py
  google/cloud/forseti/services/inventory/crawler.py
  google/cloud/forseti/services/inventory/inventory.py
  google/cloud/forseti/services/inventory/service.py
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/model/modeller.py
  google/cloud/forseti/services/model/service.py
  google/cloud/forseti/services/playground/playgrounder.py
  google/cloud/forseti/services/playground/service.py
  google/cloud/forseti/services/server.py
  google/cloud/forseti/services/utils.py
  tests/services/dao_test.py
Labels: cla: yes, status: in-progress

#1164 Deprecate Playground and denormalize
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/dao.py
  google/cloud/forseti/services/explain/explain.proto
  google/cloud/forseti/services/explain/explainer.py
  google/cloud/forseti/services/explain/service.py
  google/cloud/forseti/services/playground/.grpc_service
  google/cloud/forseti/services/playground/__init__.py
  google/cloud/forseti/services/playground/playground.proto
  google/cloud/forseti/services/playground/playgrounder.py
  google/cloud/forseti/services/playground/service.py
  google/cloud/forseti/services/server.py
  tests/services/api_tests/inventory_test.py
  tests/services/api_tests/model_test.py
  tests/services/api_tests/playground_test.py
  tests/services/cli_test.py
  tests/services/dao_test.py
  tests/services/model_tester.py
Labels: cla: yes, status: in-progress

#1153 renamed installer_type to installation_type, replaced timestamp with …
  setup/gcp/installer/configs/client_config.py
  setup/gcp/installer/configs/config.py
  setup/gcp/installer/configs/server_config.py
  setup/gcp/installer/forseti_client_installer.py
  setup/gcp/installer/forseti_installer.py
  setup/gcp/installer/forseti_server_installer.py
  setup/gcp/installer/util/constants.py
  setup/gcp/installer/util/gcloud.py
  setup/gcp/installer/util/utils.py
Labels: cla: yes, status: in-progress

#1157 Remove gflag usage in favor of argparse
  google/cloud/forseti/enforcer/enforcer.py
  requirements.txt
  setup.py
  tests/enforcer/enforcer_test.py
Labels: cla: yes, status: in-progress

#1167 Check for encrypted vars before using them in the build
  .travis.yml
  _config.yml
  travis/jekyll_build.sh
Labels: cla: yes, status: in-progress

#1175 Update gsuite-group-collection.md
  _docs/howto/configure/gsuite-group-collection.md
Labels: cla: yes, status: in-progress

#1173 Entry point cleanup for command line access
  .travis.yml
  google/cloud/forseti/stubs.py
  setup/docker/forseti
  setup/scripts/install_forseti_docker.sh
  setup/scripts/lint_forseti_docker.sh
  setup/scripts/test_forseti_docker.sh
Labels: cla: yes, status: in-progress
