Repository forseti-security/forseti-security, pull requests merged in 2018-03, with the labels that each got.

#1183 Fix datetime json serialization error in notifier
  google/cloud/forseti/notifier/notifier.py
  tests/notifier/notifier_test.py
Labels: cla: yes, status: in-progress

#1177 Installer clean up
  setup/gcp/installer/configs/config.py
  setup/gcp/installer/configs/server_config.py
  setup/gcp/installer/forseti_installer.py
  setup/gcp/installer/forseti_server_installer.py
  setup/gcp/installer/util/constants.py
  setup/gcp/installer/util/files.py
  setup/gcp/installer/util/gcloud.py
  setup/gcp/installer/util/utils.py
  setup/gcp/run_forseti_installer.py
Labels: cla: yes, status: in-progress

#1185 Fix the construction of IAM policy 'full_name'.
  google/cloud/forseti/services/model/importer/importer.py
  tests/services/model/importer/importer_test.py
Labels: cla: yes, status: in-progress

#1189 Installer should use only the last 4 characters of a datetimestamp instead of the full timestamp
  setup/gcp/installer/forseti_installer.py
  setup/gcp/installer/forseti_server_installer.py
  setup/gcp/installer/util/constants.py
  setup/gcp/installer/util/files.py
Labels: cla: yes, status: in-progress

#1190 Remove usuage of project_dao
  google/cloud/forseti/scanner/scanners/instance_network_interface_scanner.py
Labels: cla: yes, status: in-progress

#1191 Improve created_at field in the violations table
  google/cloud/forseti/common/util/string_formats.py
  google/cloud/forseti/services/scanner/dao.py
  tests/services/scanner/scanner_dao_test.py
Labels: cla: yes, status: in-progress

#1193 Fix a couple of bugs for sending out group violation notifications.
  google/cloud/forseti/scanner/scanners/groups_scanner.py
  google/cloud/forseti/services/scanner/dao.py
Labels: cla: yes, status: in-progress

#1178 Fix the Travis install process
  .travis.yml
  setup/docker/base
  setup/docker/forseti
  setup/scripts/docker_install_forseti.sh
  setup/scripts/docker_pylint_forseti.sh
  setup/scripts/docker_setup_forseti.sh
  setup/scripts/docker_unittest_forseti.sh
  tests/unittest_utils.py
Labels: cla: yes, status: in-progress

#1195 Findings Notification
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/notifier/pipelines/findings_pipeline.py
  google/cloud/forseti/scanner/scanners/groups_scanner.py
  google/cloud/forseti/services/scanner/dao.py
  tests/notifier/notifier_test.py
  tests/notifier/pipelines/findings_pipeline_test.py
  tests/services/scanner/scanner_dao_test.py
Labels: cla: yes, status: in-progress

#1197 Set better defaults for findings notification
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
Labels: cla: yes, status: in-progress

#1194 Updating the installation console output
  deployment-templates/compute-engine/client/forseti-instance-client.py
  google/cloud/forseti/common/util/string_formats.py
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/scanner/scanners/instance_network_interface_scanner.py
  google/cloud/forseti/services/scanner/dao.py
  setup/gcp/installer/forseti_client_installer.py
  setup/gcp/installer/forseti_installer.py
  setup/gcp/installer/forseti_server_installer.py
  setup/gcp/installer/util/constants.py
  setup/gcp/installer/util/gcloud.py
  setup/gcp/installer/util/utils.py
  setup/gcp/run_forseti_installer.py
  tests/gcp/installer/util/gcloud_test.py
  tests/notifier/notifier_test.py
  tests/services/scanner/scanner_dao_test.py
Labels: cla: yes, status: in-progress

#1201 Added error handling when user doesn't have access to get org info
  deployment-templates/compute-engine/client/forseti-instance-client.py
  deployment-templates/compute-engine/server/forseti-instance-server.py
  setup/gcp/installer/forseti_client_installer.py
  setup/gcp/installer/forseti_server_installer.py
  setup/gcp/installer/util/gcloud.py
  tests/gcp/installer/util/gcloud_test.py
Labels: cla: yes, status: in-progress

#1168 GCS bucket IAM scanner
  google/cloud/forseti/common/gcp_type/bucket.py
  google/cloud/forseti/common/gcp_type/iam_policy.py
  google/cloud/forseti/common/gcp_type/resource.py
  google/cloud/forseti/common/gcp_type/resource_util.py
  google/cloud/forseti/scanner/audit/iam_rules_engine.py
  google/cloud/forseti/scanner/scanners/iam_rules_scanner.py
  tests/common/gcp_type/iam_policy_test.py
  tests/scanner/audit/data/test_rules.py
  tests/scanner/audit/iam_rules_engine_test.py
  tests/scanner/scanners/iam_rules_scanner_test.py
Labels: cla: yes, status: in-progress

#1204 Log message too long
  google/cloud/forseti/common/util/logger.py
Labels: cla: yes, status: in-progress

#1207 Temporary fix for ke url doesn't contain
  google/cloud/forseti/services/inventory/base/resources.py
Labels: cla: yes, status: in-progress

#1208 Move the iam binding logging from warning to debug.
  google/cloud/forseti/common/gcp_type/iam_policy.py
Labels: cla: yes, status: in-progress

#1209 Added timeout and retry when executing command
  setup/gcp/installer/util/gcloud.py
  setup/gcp/installer/util/utils.py
Labels: cla: yes, status: in-progress

#1211 Increased default wait time to 60 seconds because some of the APIs do take that long to enable.
  setup/gcp/installer/util/utils.py
Labels: cla: yes, status: in-progress

#1215 Updated the default timeout to be 90s
  setup/gcp/installer/util/constants.py
  setup/gcp/installer/util/utils.py
Labels: cla: yes, status: in-progress

#1216 The default timeout while enabling api should be 120s
  setup/gcp/installer/util/gcloud.py
Labels: cla: yes, status: in-progress

#1219 Added quiet flag to gcloud compute ssh command
  setup/gcp/installer/util/gcloud.py
Labels: cla: yes, status: in-progress

#1115 updating configure index.md
  _docs/configure/index.md
  _docs/configure/notifier/index.md
Labels: cla: yes, status: in-progress

#1237 Fix group_email to use @googlegroups.com
  rules/bigquery_rules.yaml
Labels: cla: yes

#1212 Update README.md
  README.md
Labels: cla: yes, status: in-progress

#1213 Update README.md
  README.md
Labels: cla: yes, status: in-progress

#1214 Update README.md
  README.md
Labels: cla: yes, status: in-progress

#1241 Resource table integrity errors (fixed only for cloud sql instance)
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/utils.py
Labels: cla: yes, status: in-progress

#1238 Updated model warnings to log to debug level
  google/cloud/forseti/services/dao.py
  google/cloud/forseti/services/model/importer/importer.py
Labels: cla: yes, status: in-progress

#1244 Regex match
  google/cloud/security/common/gcp_type/iam_policy.py
  google/cloud/security/common/util/regex_util.py
  tests/common/gcp_type/iam_policy_test.py
Labels: cla: yes, status: in-progress

#1246 Forseti 2.0 CLI help should shows 'forseti' instead of 'cli.pyc'
  google/cloud/forseti/services/cli.py
Labels: cla: yes, status: in-progress

#1245 Cherry pick regex match fix into 2.0
  google/cloud/forseti/common/gcp_type/iam_policy.py
  google/cloud/forseti/common/util/regular_exp.py
  tests/common/gcp_type/iam_policy_test.py
Labels: cla: yes, status: in-progress

#1247 Add support for fetching ServerConfig from a KE Location.
  google/cloud/forseti/common/gcp_api/_supported_apis.py
  google/cloud/forseti/common/gcp_api/container.py
  google/cloud/forseti/services/inventory/base/gcp.py
  google/cloud/forseti/services/inventory/base/resources.py
  tests/common/gcp_api/container_test.py
  tests/common/gcp_api/test_data/fake_container_responses.py
  tests/services/inventory/gcp_api_mocks.py
Labels: cla: yes, status: in-progress

#1249 Allow all users to use cli
  deployment-templates/compute-engine/client/forseti-instance-client.py
  deployment-templates/compute-engine/server/forseti-instance-server.py
  setup/gcp/scripts/run_forseti.sh
Labels: cla: yes, status: in-progress

#1250 Sessionmake log message should be at debug level
  google/cloud/forseti/services/dao.py
Labels: cla: yes, status: in-progress

#1248 Update Kubernetes Engine critical CVE rule.
  rules/ke_rules.yaml
Labels: cla: yes, status: in-progress

#1253 fix forsetisecurity.org links in installer script
  scripts/gcp_setup/environment/gcloud_env.py
Labels: cla: yes

#1228 Merge 2.0-rc1 changes back to 2.0-dev
  setup/gcp/installer/util/constants.py
  setup/gcp/installer/util/gcloud.py
  setup/gcp/installer/util/utils.py
Labels: cla: yes, status: in-progress

#1196 Consolidate our use of datetime and standardize the way we store them
  google/cloud/forseti/common/gcp_api/bigquery.py
  google/cloud/forseti/common/gcp_type/firewall_rule.py
  google/cloud/forseti/common/util/date_time.py
  google/cloud/forseti/common/util/string_formats.py
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/notifier/pipelines/email_inventory_snapshot_summary_pipeline.py
  google/cloud/forseti/notifier/pipelines/email_scanner_summary_pipeline.py
  google/cloud/forseti/notifier/pipelines/email_violations_pipeline.py
  google/cloud/forseti/notifier/pipelines/findings_pipeline.py
  google/cloud/forseti/notifier/pipelines/gcs_violations_pipeline.py
  google/cloud/forseti/notifier/pipelines/slack_webhook_pipeline.py
  google/cloud/forseti/scanner/scanner.py
  google/cloud/forseti/scanner/scanners/base_scanner.py
  google/cloud/forseti/scanner/scanners/firewall_rules_scanner.py
  google/cloud/forseti/scanner/scanners/iam_rules_scanner.py
  google/cloud/forseti/scanner/scanners/iap_scanner.py
  google/cloud/forseti/services/dao.py
  google/cloud/forseti/services/inventory/base/resources.py
  google/cloud/forseti/services/inventory/base/storage.py
  google/cloud/forseti/services/inventory/inventory.proto
  google/cloud/forseti/services/inventory/service.py
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/scanner/dao.py
  tests/common/util/date_time_test.py
  tests/notifier/pipelines/findings_pipeline_test.py
  tests/notifier/pipelines/gcs_violations_pipeline_test.py
  tests/scanner/iap_scanner_test.py
  tests/scanner/scanner_test.py
  tests/scanner/scanners/firewall_rules_scanner_test.py
  tests/scanner/scanners/iam_rules_scanner_test.py
  tests/services/model/importer/importer_test.py
  tests/services/model/importer/test_data/forseti-test.db
  tests/services/model/importer/update_test_dbs.py
Labels: cla: yes, status: in-progress

#1252 Added enable_console_log flag on the server
  google/cloud/forseti/common/util/logger.py
  google/cloud/forseti/services/server.py
Labels: cla: yes, status: in-progress

#1255 Setup the client progress streaming for notifier and scanner.
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/scanner/scanner.py
  google/cloud/forseti/services/cli.py
  google/cloud/forseti/services/notifier/notifier.proto
  google/cloud/forseti/services/notifier/service.py
  google/cloud/forseti/services/scanner/scanner.proto
  google/cloud/forseti/services/scanner/service.py
  tests/services/cli_test.py
Labels: cla: yes, status: in-progress

#1251 Port findings notification to 1.0
  configs/forseti_conf.yaml.in
  configs/forseti_conf.yaml.sample
  google/cloud/security/common/data_access/sql_queries/create_tables.py
  google/cloud/security/common/data_access/sql_queries/load_data.py
  google/cloud/security/common/data_access/violation_dao.py
  google/cloud/security/common/data_access/violation_format.py
  google/cloud/security/notifier/notifier.py
  google/cloud/security/notifier/pipelines/cscc_pipeline.py
  tests/common/data_access/violation_dao_test.py
  tests/notifier/pipelines/cscc_pipeline_test.py
Labels: cla: yes, status: in-progress

#1268 Update Kubernetes Engine scanner rules.
  rules/ke_rules.yaml
Labels: cla: yes, status: in-progress

#1270 Remove the redundant use of pipelines in module names
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/notifier/notifiers/__init__.py
  google/cloud/forseti/notifier/notifiers/base_email_notification.py
  google/cloud/forseti/notifier/notifiers/base_notification.py
  google/cloud/forseti/notifier/notifiers/email_inventory_snapshot_summary.py
  google/cloud/forseti/notifier/notifiers/email_scanner_summary.py
  google/cloud/forseti/notifier/notifiers/email_violations.py
  google/cloud/forseti/notifier/notifiers/findings.py
  google/cloud/forseti/notifier/notifiers/gcs_violations.py
  google/cloud/forseti/notifier/notifiers/slack_webhook.py
  google/cloud/forseti/services/inventory/base/resources.py
  google/cloud/forseti/services/scanner/dao.py
  tests/notifier/notifiers/__init__.py
  tests/notifier/notifiers/email_inventory_snapshot_summary_test.py
  tests/notifier/notifiers/email_scanner_summary_test.py
  tests/notifier/notifiers/findings_test.py
  tests/notifier/notifiers/gcs_violations_test.py
  tests/notifier/notifiers/slack_webhook_test.py
Labels: cla: yes, status: in-progress

#1271 Corrected the order of the args when calling function _swap_config_fields
  setup/gcp/installer/forseti_server_installer.py
Labels: cla: yes, status: in-progress

#1273 duplicated member_cache_policies session add fix
  google/cloud/forseti/services/model/importer/importer.py
Labels: cla: yes, status: in-progress

#1276 Fixes for Release 1.1.11
  configs/forseti_conf.yaml.in
  configs/forseti_conf.yaml.sample
  google/cloud/security/__init__.py
  google/cloud/security/notifier/notifier.py
  google/cloud/security/notifier/pipelines/cscc_pipeline.py
  scripts/gcp_setup/environment/gcloud_env.py
  tests/notifier/notifier_test.py
  tests/notifier/pipelines/cscc_pipeline_test.py
Labels: cla: yes, status: in-progress

#1278 More Fix for 1.1.11 release; remove trailing slash for cscc bucket path.
  configs/forseti_conf.yaml.in
  configs/forseti_conf.yaml.sample
Labels: cla: yes, status: in-progress

#1279 Fixed notifier bug.
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/notifier/notifier.py
Labels: cla: yes, status: in-progress

#1260 Remove scanner notification behavior
  configs/server/forseti_conf_server.yaml.in
  google/cloud/forseti/scanner/scanners/firewall_rules_scanner.py
  google/cloud/forseti/scanner/scanners/iam_rules_scanner.py
  google/cloud/forseti/scanner/scanners/iap_scanner.py
  tests/scanner/iap_scanner_test.py
  tests/scanner/scanners/firewall_rules_scanner_test.py
  tests/scanner/scanners/iam_rules_scanner_test.py
Labels: cla: yes, status: in-progress

#1288 Email/GCS violation notifiers now use CSV
  google/cloud/forseti/common/data_access/csv_writer.py
  google/cloud/forseti/common/email_templates/notification_summary.jinja
  google/cloud/forseti/common/util/string_formats.py
  google/cloud/forseti/notifier/notifiers/email_violations.py
  google/cloud/forseti/notifier/notifiers/gcs_violations.py
  tests/notifier/notifiers/email_violations_test.py
  tests/notifier/notifiers/gcs_violations_test.py
  tests/notifier/notifiers/test_data/__init__.py
  tests/notifier/notifiers/test_data/expected_attachment.csv
Labels: cla: yes, status: in-progress

#1282 Update the merge functionality to handle the notifier section in forseti_server_config.yaml
  setup/gcp/installer/forseti_server_installer.py
  tests/gcp/installer/util/functional_test.py
  tests/gcp/installer/util/test_data/expected_merged_forseti_conf_server_from_1.1.10.yaml
  tests/gcp/installer/util/test_data/expected_merged_forseti_conf_server_from_1.1.6.yaml
  tests/gcp/installer/util/test_data/expected_merged_forseti_conf_server_from_1.1.9.yaml
  tests/gcp/installer/util/test_data/merge_from_forseti_conf_1.1.6.yaml
  tests/gcp/installer/util/test_data/merge_to_forseti_conf_server.yaml
Labels: cla: yes, status: in-progress

#1291 Create a full_name for group violation data
  google/cloud/forseti/scanner/scanners/groups_scanner.py
Labels: cla: yes, status: in-progress

#1289 Updated run_forseti.sh to handle long model creation time
  setup/gcp/scripts/run_forseti.sh
Labels: cla: yes, status: in-progress

#1295 Added error handling for scanner and notifier cli
  google/cloud/forseti/scanner/scanner.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/notifier/service.py
  google/cloud/forseti/services/scanner/service.py
Labels: cla: yes, status: in-progress

#1277 Rename sql columns
  google/cloud/forseti/notifier/notifiers/findings.py
  google/cloud/forseti/scanner/audit/bigquery_rules_engine.py
  google/cloud/forseti/scanner/audit/blacklist_rules_engine.py
  google/cloud/forseti/scanner/audit/buckets_rules_engine.py
  google/cloud/forseti/scanner/audit/cloudsql_rules_engine.py
  google/cloud/forseti/scanner/audit/firewall_rules_engine.py
  google/cloud/forseti/scanner/audit/forwarding_rule_rules_engine.py
  google/cloud/forseti/scanner/audit/iam_rules_engine.py
  google/cloud/forseti/scanner/audit/iap_rules_engine.py
  google/cloud/forseti/scanner/audit/instance_network_interface_rules_engine.py
  google/cloud/forseti/scanner/audit/ke_version_rules_engine.py
  google/cloud/forseti/scanner/audit/rules.py
  google/cloud/forseti/scanner/scanners/bigquery_scanner.py
  google/cloud/forseti/scanner/scanners/blacklist_scanner.py
  google/cloud/forseti/scanner/scanners/bucket_rules_scanner.py
  google/cloud/forseti/scanner/scanners/cloudsql_rules_scanner.py
  google/cloud/forseti/scanner/scanners/firewall_rules_scanner.py
  google/cloud/forseti/scanner/scanners/forwarding_rule_scanner.py
  google/cloud/forseti/scanner/scanners/groups_scanner.py
  google/cloud/forseti/scanner/scanners/iam_rules_scanner.py
  google/cloud/forseti/scanner/scanners/iap_scanner.py
  google/cloud/forseti/scanner/scanners/instance_network_interface_scanner.py
  google/cloud/forseti/scanner/scanners/ke_version_scanner.py
  google/cloud/forseti/services/client.py
  google/cloud/forseti/services/inventory/base/resources.py
  google/cloud/forseti/services/inventory/inventory.py
  google/cloud/forseti/services/inventory/service.py
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/model/modeller.py
  google/cloud/forseti/services/scanner/dao.py
  google/cloud/forseti/services/utils.py
  tests/common/util/metadata_server_test.py
  tests/notifier/notifiers/email_scanner_summary_test.py
  tests/notifier/notifiers/findings_test.py
  tests/scanner/audit/bigquery_rules_engine_test.py
  tests/scanner/audit/firewall_rules_engine_test.py
  tests/scanner/audit/iam_rules_engine_test.py
  tests/scanner/audit/iap_rules_engine_test.py
  tests/scanner/iap_scanner_test.py
  tests/scanner/scanners/firewall_rules_scanner_test.py
  tests/scanner/scanners/ke_version_scanner_test.py
  tests/scanner/test_data/fake_bigquery_scanner_data.py
  tests/scanner/test_data/fake_blacklist_scanner_data.py
  tests/services/model/importer/importer_test.py
  tests/services/model/importer/test_data/forseti-test.db
  tests/services/scanner/scanner_dao_test.py
Labels: cla: yes, status: in-progress

#1292 Improved import of CSV files into Google sheets
  google/cloud/forseti/common/data_access/csv_writer.py
  tests/notifier/notifiers/test_data/expected_attachment.csv
Labels: cla: yes, status: in-progress

#1303 Removed outdated setup_forseti.py reference in code
  setup/gcp/installer/util/constants.py
  setup/gcp/scripts/initialize_forseti_services.sh
Labels: cla: yes, status: in-progress

#1302 Remove initial inventory/scan from installation, removed unnecessary references to ubuntu
  deployment-templates/compute-engine/server/forseti-instance-server.py
Labels: cla: yes, status: in-progress

#1301 Allow user to specify the violation payload format (csv / json)
  google/cloud/forseti/notifier/notifiers/base_notification.py
  google/cloud/forseti/notifier/notifiers/email_violations.py
  google/cloud/forseti/notifier/notifiers/gcs_violations.py
  tests/notifier/notifiers/email_violations_test.py
  tests/notifier/notifiers/gcs_violations_test.py
  tests/notifier/notifiers/test_data/expected_attachment.csv
  tests/notifier/notifiers/test_data/fake_violations.py
Labels: cla: yes

#1304 Update the storage API client to handler Requester Pays buckets.
  google/cloud/forseti/common/gcp_api/storage.py
  google/cloud/forseti/common/util/metadata_server.py
  setup/gcp/installer/util/constants.py
  tests/common/gcp_api/storage_test.py
  tests/common/gcp_api/test_data/fake_storage_responses.py
  tests/common/util/metadata_server_test.py
Labels: cla: yes, status: in-progress

#1305 Revert "Update the storage API client to handler Requester Pays bucke…
  google/cloud/forseti/common/gcp_api/storage.py
  google/cloud/forseti/common/util/metadata_server.py
  setup/gcp/installer/util/constants.py
  tests/common/gcp_api/storage_test.py
  tests/common/gcp_api/test_data/fake_storage_responses.py
  tests/common/util/metadata_server_test.py
Labels: cla: yes, status: in-progress

#1290 Notifier will not send/upload empty violation attachments any more
  tests/notifier/notifier_test.py
  tests/notifier/notifiers/test_data/fake_violations.py
Labels: cla: yes, status: in-progress

#1309 Added sudo when using gsutil cp in run_forseti.sh
  setup/gcp/scripts/run_forseti.sh
Labels: cla: yes, status: in-progress

#1310 Remove storage.objectCreator role from client service account
  setup/gcp/installer/util/constants.py
Labels: cla: yes, status: in-progress

#1311 Merge 2.0-dev into 2.0-rc2
  setup/gcp/scripts/run_forseti.sh
Labels: cla: yes, status: in-progress

#1130 Added installation documentation.
  _docs/_latest/setup/change-gcp-deployment.md
  _docs/_latest/setup/gcp-deployment.md
  _docs/_latest/setup/index.md
  _docs/_latest/setup/install-forseti-security.md
Labels: cla: no, status: in-progress

#1320 Service accounts 2.0
  _docs/_latest/concepts/forseti-service-accounts.md
  images/docs/concepts/service-account-architecture.png
Labels: cla: yes, status: in-progress

#1321 Create best-practices.md
  _docs/_latest/concepts/best-practices.md
Labels: cla: yes, status: in-progress

#1322 2.0 landing pages
  _docs/_latest/concepts/index.md
  _docs/_latest/configure/forseti/index.md
  _docs/_latest/configure/index.md
  _docs/_latest/develop/index.md
  _docs/_latest/index.md
  _docs/_latest/setup/index.md
  _docs/_latest/setup/install.md
  _docs/_latest/use/index.md
Labels: cla: yes, status: in-progress
