Repository forseti-security/forseti-security, pull requests merged in 2019-04, with the labels that each got.

#2649 scanner working with inventory changes
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/common/data_access/violation_map.py
  google/cloud/forseti/common/gcp_type/groups_settings.py
  google/cloud/forseti/common/gcp_type/resource.py
  google/cloud/forseti/common/gcp_type/resource_util.py
  google/cloud/forseti/scanner/audit/groups_settings_rules_engine.py
  google/cloud/forseti/scanner/scanner_requirements_map.py
  google/cloud/forseti/scanner/scanners/groups_settings_scanner.py
  google/cloud/forseti/services/dao.py
  rules/groups_settings_rules.yaml
  tests/scanner/scanners/data/groups_settings_scanner_test_rules.yaml
  tests/scanner/scanners/groups_settings_scanner_test.py
  tests/scanner/test_data/fake_groups_settings_scanner_data.py
Labels: cla: yes, status: in-progress

#2659 Update ke_scanner_rules.yaml with CIS Benchmark Examples
  rules/ke_scanner_rules.yaml
Labels: cla: yes

#2683 Tests updated to align with GA API
  google/cloud/forseti/common/gcp_api/securitycenter.py
  google/cloud/forseti/notifier/notifiers/cscc_notifier.py
  tests/common/gcp_api/securitycenter_test.py
  tests/notifier/notifiers/cscc_notifier_test.py
Labels: cla: yes, status: in-progress

#2687 Updated config file to sync with GA API migration
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
Labels: cla: yes, status: in-progress

#2670 updated website docs to reflect gsuite change
  _docs/_latest/configure/inventory/gsuite.md
  _docs/_latest/configure/scanner/rules.md
Labels: cla: yes, status: in-progress

#2686 Update README after 1.0 Has Been Deprecated
  README.md
Labels: cla: yes, status: in-progress

#2688 Forseti day blog post
  _news/2019-04-01-forseti-community-day-sfo-2.md
Labels: cla: yes, status: in-progress

#2691 Update policy-library path.
  deployment-templates/compute-engine/server/forseti-instance-server.py
  install/gcp/scripts/initialize_forseti_services.sh
Labels: cla: yes, status: in-progress

#2674 Add documentation for defining custom firewall rules scanner
  _docs/_latest/configure/scanner/rules.md
Labels: cla: yes

#2695 Documentation for Forseti Real Time Enforcer
  _docs/_latest/concepts/index.md
  _docs/_latest/concepts/real-time-enforcer.md
  _docs/_latest/concepts/service-accounts.md
  _docs/_latest/configure/index.md
  _docs/_latest/configure/real-time-enforcer/default-policies.md
  _docs/_latest/configure/real-time-enforcer/index.md
  _docs/_latest/configure/real-time-enforcer/opa-engine.md
  _docs/_latest/configure/real-time-enforcer/resources.md
  _docs/_latest/setup/index.md
  _docs/_latest/setup/real-time-enforcer.md
  _includes/docs/latest/beta-release-feature.md
  _includes/docs/latest/cloud-foundation-forseti-enforcer-required-roles.md
  _includes/docs/latest/cloud-foundation-forseti-required-roles.md
  _includes/docs/latest/forseti-enforcer-gcp-required-roles.md
Labels: cla: yes, status: in-progress

#2696 upgrade instructions for 2.13 -> 2.14
  _docs/_latest/setup/install.md
  _docs/_latest/setup/upgrade.md
Labels: cla: yes, status: in-progress

#2703 Forseti Day 19 schedule as image
  _news/2019-04-01-forseti-community-day-sfo-2.md
  images/news/forseti_day_19.png
Labels: cla: yes, status: in-progress

#2705 Forseti community day blog post
  _docs/_latest/concepts/index.md
  _docs/_latest/concepts/real-time-enforcer.md
  _docs/_latest/concepts/service-accounts.md
  _docs/_latest/configure/index.md
  _docs/_latest/configure/real-time-enforcer/default-policies.md
  _docs/_latest/configure/real-time-enforcer/index.md
  _docs/_latest/configure/real-time-enforcer/opa-engine.md
  _docs/_latest/configure/real-time-enforcer/resources.md
  _docs/_latest/configure/scanner/rules.md
  _docs/_latest/setup/index.md
  _docs/_latest/setup/install.md
  _docs/_latest/setup/real-time-enforcer.md
  _docs/_latest/setup/upgrade.md
  _includes/docs/latest/beta-release-feature.md
  _includes/docs/latest/cloud-foundation-forseti-enforcer-required-roles.md
  _includes/docs/latest/cloud-foundation-forseti-required-roles.md
  _includes/docs/latest/forseti-enforcer-gcp-required-roles.md
  _news/2019-04-01-forseti-community-day-sfo-2.md
  images/news/forseti_day_19.png
Labels: cla: yes, status: in-progress

#2701 config validator scanner doc
  _docs/_latest/configure/scanner/descriptions.md
Labels: cla: yes, status: in-progress

#2709 Disable iterating ke data from cai
  google/cloud/forseti/services/inventory/base/cai_gcp_client.py
  tests/services/inventory/crawling_test.py
  tests/services/inventory/test_data/mock_cai_iam_policies.dump
  tests/services/inventory/test_data/mock_cai_resources.dump
  tests/services/inventory/update_cai_dumps.py
Labels: cla: yes, status: in-progress

#2711 Timesketch terraform release 2.14.0
  contrib/incident-response/README.md
  contrib/incident-response/infrastructure/LICENSE
  contrib/incident-response/infrastructure/README.md
  contrib/incident-response/infrastructure/main.tf
  contrib/incident-response/infrastructure/modules/timesketch/README.md
  contrib/incident-response/infrastructure/modules/timesketch/main.tf
  contrib/incident-response/infrastructure/modules/timesketch/outputs.tf
  contrib/incident-response/infrastructure/modules/timesketch/templates/scripts/install-elasticsearch.sh.tpl
  contrib/incident-response/infrastructure/modules/timesketch/templates/scripts/install-timesketch.sh.tpl
  contrib/incident-response/infrastructure/modules/timesketch/variables.tf
  contrib/incident-response/infrastructure/outputs.tf
  contrib/incident-response/infrastructure/variables.tf
Labels: cla: no, status: in-progress

#2650 Timesketch terraform
  contrib/incident-response/README.md
  contrib/incident-response/infrastructure/LICENSE
  contrib/incident-response/infrastructure/README.md
  contrib/incident-response/infrastructure/main.tf
  contrib/incident-response/infrastructure/modules/timesketch/README.md
  contrib/incident-response/infrastructure/modules/timesketch/main.tf
  contrib/incident-response/infrastructure/modules/timesketch/outputs.tf
  contrib/incident-response/infrastructure/modules/timesketch/templates/scripts/install-elasticsearch.sh.tpl
  contrib/incident-response/infrastructure/modules/timesketch/templates/scripts/install-timesketch.sh.tpl
  contrib/incident-response/infrastructure/modules/timesketch/variables.tf
  contrib/incident-response/infrastructure/outputs.tf
  contrib/incident-response/infrastructure/variables.tf
Labels: cla: yes

#2719 Revert "Update ke_scanner_rules.yaml with CIS Benchmark Examples"
  rules/ke_scanner_rules.yaml
Labels: cla: yes, status: in-progress

#2720 Updated upgrade instructions to include adding GSuite groups settings scope
  _docs/_latest/setup/upgrade.md
  _docs/v2.14/setup/upgrade.md
Labels: cla: yes, status: in-progress

#2722 Updated upgrade instructions to include adding GSuite groups settings…
  _docs/_latest/setup/upgrade.md
  _docs/v2.14/setup/upgrade.md
Labels: cla: yes, status: in-progress

#2723 Website now shows latest posts first
  _config.yml
  news/index.html
Labels: cla: yes, status: in-progress

#2608 Remove service account limit per firewall rule.
  google/cloud/forseti/common/gcp_type/firewall_rule.py
  tests/common/gcp_type/firewall_rule_test.py
Labels: cla: yes

#2465 custom role permission scanner
  google/cloud/forseti/common/data_access/violation_map.py
  google/cloud/forseti/common/gcp_type/resource.py
  google/cloud/forseti/common/gcp_type/resource_util.py
  google/cloud/forseti/common/gcp_type/role.py
  google/cloud/forseti/scanner/audit/role_rules_engine.py
  google/cloud/forseti/scanner/scanner_requirements_map.py
  google/cloud/forseti/scanner/scanners/role_scanner.py
  rules/role_rules.yaml
  tests/common/gcp_type/role_test.py
  tests/scanner/audit/role_rules_engine_test.py
  tests/scanner/scanners/role_scanner_test.py
  tests/scanner/test_data/fake_role_scanner_data.py
Labels: cla: yes, status: in-progress

#2724 Removed gmail from default group policy.
  rules/group_rules.yaml
Labels: cla: yes, status: in-progress

#2730 Added config validator blogpost
  _news/2019-04-10-config-validator.md
  images/news/2019-04-10-config-validator.png
Labels: cla: yes, status: in-progress

#2732 Added config validator blogpost (#2730)
  _news/2019-04-10-config-validator.md
  images/news/2019-04-10-config-validator.png
Labels: cla: yes, status: in-progress

#2738 Updated config validator blog post image.
  images/news/2019-04-10-config-validator.png
Labels: cla: yes, status: in-progress

#2736 Allow grpc client to receive large messages.
  google/cloud/forseti/services/client.py
Labels: cla: yes, status: in-progress

#2745 Upgraded jinja2 to 2.10.1.
  setup.py
Labels: cla: yes

#2747 Updated Enforcer FAQ
  _docs/_latest/configure/real-time-enforcer/opa-engine.md
  _docs/_latest/configure/scanner/descriptions.md
  _docs/v2.14/configure/scanner/descriptions.md
  _faq/resource/enforcers.md
  _news/2019-04-10-config-validator.md
Labels: cla: yes

#2753 Added FAQ and working links
  _docs/_latest/configure/real-time-enforcer/opa-engine.md
  _docs/_latest/configure/scanner/descriptions.md
  _docs/v2.14/configure/scanner/descriptions.md
  _faq/resource/enforcers.md
  _news/2019-04-10-config-validator.md
Labels: cla: yes

#2751 Update location scanner doc to include supported resource types
  _docs/_latest/configure/scanner/rules.md
Labels: cla: yes

#2755 Improved documentation around External project access scanner
  _docs/_latest/use/cli/scanner.md
Labels: cla: yes

#2767 Increased config validator grpc packet size to 1gb.
  google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py
Labels: cla: yes

#2765 CSCC documentation update
  _docs/_latest/configure/notifier/index.md
Labels: cla: yes

#2783 Updated config validator violation to include violation message properly.
  google/cloud/forseti/services/scanner/dao.py
  tests/services/scanner/scanner_dao_test.py
Labels: cla: yes

#2782 Updated resource_name in IAM violation to reflect the resource name i…
  google/cloud/forseti/scanner/scanners/iam_rules_scanner.py
Labels: cla: yes
