Repository forseti-security/forseti-security, pull requests merged in 2019-02, with the labels that each got.

#2440 k8s Services
  google/cloud/forseti/services/inventory/service.py
  install/docker/cloudbuild.yaml
  install/scripts/cloudsqlproxy.service.template.yaml
  install/scripts/cloudsqlproxy.template.yaml
  install/scripts/docker_entrypoint.sh
  install/scripts/forseti.client.template.yaml
  install/scripts/forseti.server.service.template.yaml
  install/scripts/forseti.server.template.yaml
  install/scripts/k8s_setup_forseti.sh
Labels: cla: yes, status: in-progress

#2497 Assign Project IAM roles immediately after creating server and client service accounts
  install/gcp/installer/forseti_client_installer.py
  install/gcp/installer/forseti_server_installer.py
Labels: cla: yes, status: in-progress

#2524 k8s Services Cont
  google/cloud/forseti/services/inventory/service.py
  install/docker/cloudbuild.yaml
  install/scripts/docker_entrypoint.sh
Labels: cla: yes

#2517 Updated rules to include comment to clarify resource_ids.
  rules/audit_logging_rules.yaml
  rules/bigquery_rules.yaml
  rules/cloudsql_rules.yaml
  rules/enabled_apis_rules.yaml
  rules/iam_rules.yaml
  rules/iap_rules.yaml
  rules/ke_rules.yaml
  rules/ke_scanner_rules.yaml
  rules/lien_rules.yaml
  rules/location_rules.yaml
  rules/log_sink_rules.yaml
  rules/resource_rules.yaml
  rules/retention_rules.yaml
  rules/service_account_key_rules.yaml
Labels: cla: yes, status: in-progress

#2530 Pin PIP packages to a specific version.
  requirements.txt
  setup.py
Labels: cla: yes, status: in-progress

#2528 Replace incorrect link with correct develop/dev/index.md link
  _docs/_latest/develop/index.md
  _docs/v2.0/develop/index.md
  _docs/v2.1/develop/index.md
  _docs/v2.10/develop/index.md
  _docs/v2.2/develop/index.md
  _docs/v2.3/develop/index.md
  _docs/v2.4/develop/index.md
  _docs/v2.5/develop/index.md
  _docs/v2.6/develop/index.md
  _docs/v2.7/develop/index.md
  _docs/v2.8/develop/index.md
  _docs/v2.9/develop/index.md
Labels: cla: yes, status: in-progress

#2529 Take out roles/storage.objectAdmin bullet
  _includes/docs/latest/forseti-server-gcp-required-roles.md
  _includes/docs/v2.10/forseti-server-gcp-required-roles.md
  _includes/docs/v2.5/forseti-server-gcp-required-roles.md
  _includes/docs/v2.6/forseti-server-gcp-required-roles.md
  _includes/docs/v2.7/forseti-server-gcp-required-roles.md
  _includes/docs/v2.8/forseti-server-gcp-required-roles.md
  _includes/docs/v2.9/forseti-server-gcp-required-roles.md
Labels: cla: yes, status: in-progress

#2533 Add default value for disabled attribute on firewall rules in enforcer.
  google/cloud/forseti/enforcer/gce_firewall_enforcer.py
  tests/enforcer/gce_firewall_enforcer_test.py
  tests/enforcer/testing_constants.py
Labels: cla: yes, status: in-progress

#2532 updated pyyaml to use a newer version.
  requirements.txt
  setup.py
Labels: cla: yes, status: in-progress

#2527 Initial commit to support the specification of users in External Project Access scanner rule.
  google/cloud/forseti/scanner/audit/external_project_access_rules_engine.py
  google/cloud/forseti/scanner/scanners/external_project_access_scanner.py
  tests/scanner/audit/external_project_access_engine_test.py
  tests/scanner/scanners/external_project_access_scanner_test.py
Labels: cla: yes

#2534 Switch to using firewalls.patch for firewall enforcer.
  google/cloud/forseti/common/gcp_api/compute.py
  google/cloud/forseti/common/gcp_api/repository_mixins.py
  google/cloud/forseti/enforcer/gce_firewall_enforcer.py
  tests/common/gcp_api/compute_test.py
  tests/enforcer/gce_firewall_enforcer_test.py
  tests/enforcer/project_enforcer_test.py
Labels: cla: yes, status: in-progress

#2536 Fix CAI import of CloudSQL data.
  google/cloud/forseti/services/inventory/base/cai_gcp_client.py
  google/cloud/forseti/services/inventory/base/gcp.py
  google/cloud/forseti/services/inventory/base/resources.py
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/model/importer/importer.py
  tests/services/inventory/crawling_test.py
  tests/services/inventory/test_data/additional_cai_resources.dump
  tests/services/inventory/test_data/mock_cai_resources.dump
  tests/services/inventory/test_data/mock_gcp_results.py
  tests/services/model/importer/test_data/forseti-test.db
Labels: cla: yes

#2516 Remove untested/unsupported flags (dry-run & advanced)
  install/gcp/gcp_installer.py
  install/gcp/installer/configs/config.py
  install/gcp/installer/forseti_installer.py
  install/gcp/installer/forseti_server_installer.py
  install/gcp/installer/util/files.py
  install/gcp/installer/util/gcloud.py
  install/gcp/installer/util/utils.py
Labels: cla: yes, status: in-progress

#2496 Rolling back the session on sqlalchemyerror when deleting CAI data
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/model/importer/importer.py
  tests/services/model/importer/importer_test.py
Labels: cla: yes, status: in-progress

#2542 Fix bucket rules scanner to use gcs_policy for bucket ACLs.
  google/cloud/forseti/scanner/scanners/bucket_rules_scanner.py
  google/cloud/forseti/services/model/importer/importer.py
  tests/services/model/importer/importer_test.py
Labels: cla: yes, status: in-progress

#2537 Add in resources.
  _includes/docs/latest/resource-coverage.md
Labels: cla: yes, status: in-progress

#2545 Add support for Cloud Asset folder level now that it launched.
  google/cloud/forseti/common/gcp_api/cloudasset.py
  google/cloud/forseti/services/base/config.py
  google/cloud/forseti/services/inventory/base/cloudasset.py
  tests/common/gcp_api/cloudasset_test.py
  tests/common/gcp_api/test_data/fake_cloudasset_responses.py
  tests/services/inventory/cloudasset_test.py
  tests/services/inventory/test_data/mock_cai_project3_iam_policies.dump
  tests/services/inventory/test_data/mock_cai_project3_resources.dump
  tests/services/inventory/test_data/mock_cai_project4_iam_policies.dump
  tests/services/inventory/test_data/mock_cai_project4_resources.dump
Labels: cla: yes, status: in-progress

#2507 KMS Scanner Implementation
  configs/server/forseti_conf_server.yaml.in
  google/cloud/forseti/common/data_access/violation_map.py
  google/cloud/forseti/common/gcp_type/crypto_key.py
  google/cloud/forseti/common/gcp_type/key_ring.py
  google/cloud/forseti/common/gcp_type/resource.py
  google/cloud/forseti/scanner/audit/kms_rules_engine.py
  google/cloud/forseti/scanner/scanner_requirements_map.py
  google/cloud/forseti/scanner/scanners/kms_scanner.py
  rules/kms_rules.yaml
  tests/scanner/scanners/data/kms_scanner_test_rules.yaml
  tests/scanner/scanners/kms_scanner_test.py
  tests/scanner/test_data/fake_kms_scanner_data.py
Labels: cla: yes, status: in-progress

#2541 KMS Scanner Documentation
  _docs/_latest/configure/scanner/descriptions.md
  _docs/_latest/configure/scanner/rules.md
Labels: cla: yes, status: in-progress

#2555 Fix bucket acl generation when CAI is enabled - dev
  google/cloud/forseti/__init__.py
  google/cloud/forseti/services/inventory/base/resources.py
  tests/services/inventory/test_data/mock_cai_resources.dump
  tests/services/inventory/update_cai_dumps.py
Labels: cla: yes, status: in-progress

#2554 Switch the CloudAsset temporary table to store the asset data as json - dev
  google/cloud/forseti/services/inventory/base/cai_gcp_client.py
  google/cloud/forseti/services/inventory/storage.py
  tests/services/inventory/crawling_test.py
  tests/services/model/importer/test_data/forseti-test.db
Labels: cla: yes, status: in-progress

#2557 Add slash in KMS GCS path
  configs/server/forseti_conf_server.yaml.in
Labels: cla: yes, status: in-progress

#2556 Add slash in KMS GCS path
  configs/server/forseti_conf_server.yaml.in
Labels: cla: yes, status: in-progress

#2558 Get rid of legacy notifier in resources scanner.
  configs/server/forseti_conf_server.yaml.in
Labels: cla: yes

#2559 Remove legacy notifier configuration in resources scanner.
  configs/server/forseti_conf_server.yaml.in
Labels: cla: yes, status: in-progress

#2560 ADD users parameter in EAP documentation - website
  _docs/_latest/configure/scanner/rules.md
Labels: cla: yes, status: in-progress

#2562 Add verbose mode to jekyll build to prevent timeout on travis.
  travis/jekyll_build.sh
Labels: cla: yes, status: in-progress

#2565 Handle long build time for the website.
  travis/jekyll_build.sh
Labels: cla: yes, status: in-progress

#2566 Revert travis wait
  .travis.yml
Labels: cla: yes, status: in-progress

#2567 Add Terraform in install
  _docs/_latest/setup/install.md
  _docs/v2.11/setup/install.md
Labels: cla: yes, status: in-progress

#2568 Merge forsetisecurity.org-dev into forsetisecurity.org
  _docs/_latest/setup/install.md
  _docs/v2.11/setup/install.md
Labels: cla: yes, status: in-progress

#2570 Updated log level and message to clarify db migrator action.
  install/gcp/upgrade_tools/db_migrator.py
Labels: cla: yes, status: in-progress

#2573 KMS scanner now scans for enabled keys only
  google/cloud/forseti/scanner/audit/kms_rules_engine.py
  tests/scanner/scanners/kms_scanner_test.py
  tests/scanner/test_data/fake_kms_scanner_data.py
Labels: cla: yes, status: in-progress

#2553 patch instead of create cscc findings
  google/cloud/forseti/common/gcp_api/securitycenter.py
Labels: cla: yes

#2575 Release 2.11.0
  google/cloud/forseti/scanner/audit/kms_rules_engine.py
  tests/scanner/scanners/kms_scanner_test.py
  tests/scanner/test_data/fake_kms_scanner_data.py
Labels: cla: yes, status: in-progress

#2538 Add support for crawling multiple root resources with a composite root
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/common/gcp_api/cloudasset.py
  google/cloud/forseti/services/base/config.py
  google/cloud/forseti/services/inventory/base/cloudasset.py
  google/cloud/forseti/services/inventory/base/resources.py
  google/cloud/forseti/services/inventory/crawler.py
  google/cloud/forseti/services/inventory/storage.py
  google/cloud/forseti/services/model/importer/importer.py
  google/cloud/forseti/services/utils.py
  tests/common/gcp_api/cloudasset_test.py
  tests/common/gcp_api/test_data/fake_cloudasset_responses.py
  tests/services/config_test.py
  tests/services/inventory/cloudasset_test.py
  tests/services/inventory/crawling_test.py
  tests/services/inventory/test_data/mock_cai_project3_iam_policies.dump
  tests/services/inventory/test_data/mock_cai_project3_resources.dump
  tests/services/inventory/test_data/mock_cai_project4_iam_policies.dump
  tests/services/inventory/test_data/mock_cai_project4_resources.dump
  tests/services/model/importer/importer_test.py
  tests/services/model/importer/test_data/forseti-composite-test.db
  tests/services/model/importer/test_data/forseti-test.db
  tests/services/model/importer/update_test_dbs.py
  tests/services/server_test.py
  tests/services/test_data/forseti_conf_server_composite_and_root.yaml
  tests/services/test_data/forseti_conf_server_composite_root.yaml
  tests/services/test_data/forseti_conf_server_neither_composite_nor_root.yaml
Labels: cla: yes, status: in-progress

#2586 added blog post content
  _news/2019-02-21-forseti-community-day-sfo.md
Labels: cla: yes, status: in-progress

#2587 Forsetisecurity.org dev
  _news/2019-02-21-forseti-community-day-sfo.md
Labels: cla: yes, status: in-progress

#2585 Add in contrib directory.
  contrib/__init__.py
Labels: cla: yes, status: in-progress

#2580 News for 1.0 deprecation announcement
  _news/2019-02-18-deprecate-1.0.md
Labels: cla: yes, status: in-progress

#2583 Update inventory.md
  _docs/_latest/use/cli/inventory.md
  _docs/latest/use/cli/inventory.md
  _docs/v2.0/use/cli/inventory.md
  _docs/v2.1/use/cli/inventory.md
  _docs/v2.10/use/cli/inventory.md
  _docs/v2.11/use/cli/inventory.md
  _docs/v2.2/use/cli/inventory.md
  _docs/v2.3/use/cli/inventory.md
  _docs/v2.4/use/cli/inventory.md
  _docs/v2.5/use/cli/inventory.md
  _docs/v2.6/use/cli/inventory.md
  _docs/v2.7/use/cli/inventory.md
  _docs/v2.8/use/cli/inventory.md
  _docs/v2.9/use/cli/inventory.md
Labels: cla: yes

#2592 Increased mysql connection timeout to 1 hour.
  google/cloud/forseti/services/dao.py
Labels: cla: yes, status: in-progress

#2597 Update installation message for gsuite
  install/gcp/installer/util/constants.py
Labels: cla: yes, status: in-progress

#2543 Inventory's status should be PARTIAL SUCCESS if warnings are found
  google/cloud/forseti/services/inventory/storage.py
Labels: cla: yes, status: in-progress

#2589 Updated KMS Scanner documentation with new rules
  _docs/_latest/configure/scanner/default-rules.md
  _docs/_latest/configure/scanner/descriptions.md
  _docs/_latest/configure/scanner/rules.md
Labels: cla: yes, status: in-progress

#2600 Updated version to 2.11.1
  google/cloud/forseti/__init__.py
Labels: cla: yes, status: in-progress

#2602 Release 2.11.1
  google/cloud/forseti/__init__.py
Labels: cla: yes, status: in-progress

#2601 Update inventory documentation to include details for composite root.
  _docs/latest/configure/general/non-org-root.md
  _includes/docs/latest/minimum-configuration-settings.md
Labels: cla: yes, status: in-progress

#2590 k8s cont: Enable Cron Job to Run Inside the Server in Docker
  install/dependencies/apt_packages.txt
  install/docker/cloudbuild.yaml
  install/scripts/docker_entrypoint.sh
  install/scripts/forseti.client.template.yaml
  install/scripts/forseti.cronjob.template.yaml
  install/scripts/forseti.server.template.yaml
  install/scripts/k8s_setup_forseti.sh
Labels: cla: yes

#2603 Added steps to upgrade from v2.11.0 to v2.12.0
  _docs/_latest/setup/install.md
  _docs/_latest/setup/upgrade.md
Labels: cla: yes, status: in-progress

#2335 Run Forseti in Docker on Kubernetes or Container-Optimized OS (Proof of Concept)
  .dockerignore
  install/dependencies/apt_packages.txt
  install/docker/base
  install/docker/cloudbuild.yaml
  install/docker/forseti
  install/scripts/cloudsqlproxy.service.template.yaml
  install/scripts/cloudsqlproxy.template.yaml
  install/scripts/cos_setup_forseti.sh
  install/scripts/docker_entrypoint.sh
  install/scripts/forseti.client.template.yaml
  install/scripts/forseti.cronjob.template.yaml
  install/scripts/forseti.server.service.template.yaml
  install/scripts/forseti.server.template.yaml
  install/scripts/k8s_setup_forseti.sh
Labels: cla: no, status: in-progress

#2605 v2.12.0 doc update
  _docs/_latest/configure/general/non-org-root.md
Labels: cla: yes, status: in-progress

#2604 Fix missing IAP violations
  google/cloud/forseti/services/inventory/base/cai_gcp_client.py
  tests/scanner/iap_scanner_test.py
Labels: cla: yes, status: in-progress

#2606 Updated installation steps for v2.12.0
  _docs/_latest/setup/install.md
Labels: cla: yes, status: in-progress
