Repository forseti-security/forseti-security, pull requests merged in 2019-05, with the labels that each got.

#2780 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#2775 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: cla: yes

#2774 Update README.md
  README.md
Labels: cla: yes

#2752 Account for instance types with no settings
  google/cloud/forseti/common/gcp_type/cloudsql_access_controls.py
Labels: cla: yes

#2797 Fix KMS Scanner test
  tests/scanner/scanners/kms_scanner_test.py
Labels: cla: yes

#2794 Update architecture.md
  _docs/_latest/concepts/architecture.md
  _docs/_latest/configure/notifier/index.md
  images/docs/concepts/forseti-architecture.png
Labels: cla: yes

#2791 Add support for RegionBackendService
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/services/inventory/base/cai_gcp_client.py
  google/cloud/forseti/services/inventory/base/cloudasset.py
  tests/services/inventory/crawling_test.py
  tests/services/inventory/test_data/additional_cai_resources.dump
  tests/services/inventory/test_data/mock_cai_resources.dump
Labels: cla: yes

#2771 update Bigquery rule description
  _docs/_latest/configure/scanner/descriptions.md
  _docs/latest/configure/scanner/descriptions.md
  _docs/v2.10/configure/scanner/descriptions.md
  _docs/v2.11/configure/scanner/descriptions.md
  _docs/v2.12/configure/scanner/descriptions.md
  _docs/v2.13/configure/scanner/descriptions.md
  _docs/v2.14/configure/scanner/descriptions.md
  _docs/v2.3/configure/scanner/descriptions.md
  _docs/v2.4/configure/scanner/descriptions.md
  _docs/v2.5/configure/scanner/descriptions.md
  _docs/v2.6/configure/scanner/descriptions.md
  _docs/v2.7/configure/scanner/descriptions.md
  _docs/v2.8/configure/scanner/descriptions.md
  _docs/v2.9/configure/scanner/descriptions.md
Labels: cla: yes

#2301 Add missing resource types in IAM Scanner documentation
  _docs/_latest/configure/scanner/descriptions.md
  _docs/_latest/configure/scanner/rules.md
Labels: 1 - Planning, cla: yes, status: in-progress

#2805 Add comma at the end to split the resources.
  google/cloud/forseti/services/inventory/base/cloudasset.py
Labels: cla: yes

#2810 Added instructions to install Forseti in shared VPC
  _docs/_latest/setup/install.md
Labels: cla: yes

#2818 Merge fs-future-2-15 into fs-future
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  configs/server/forseti_conf_server.yaml.in
  configs/server/forseti_conf_server.yaml.sample
  google/cloud/forseti/__init__.py
  google/cloud/forseti/common/gcp_type/cloudsql_access_controls.py
  google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py
  google/cloud/forseti/scanner/scanners/iam_rules_scanner.py
  google/cloud/forseti/services/inventory/base/cai_gcp_client.py
  google/cloud/forseti/services/inventory/base/cloudasset.py
  google/cloud/forseti/services/scanner/dao.py
  tests/scanner/audit/firewall_rules_engine_test.py
  tests/services/inventory/crawling_test.py
  tests/services/inventory/test_data/additional_cai_resources.dump
  tests/services/inventory/test_data/mock_cai_resources.dump
  tests/services/inventory/update_cai_dumps.py
  tests/services/scanner/scanner_dao_test.py
Labels: cla: yes

#2821 Merge release 2.15.0 into dev
  google/cloud/forseti/__init__.py
  google/cloud/forseti/services/inventory/base/cloudasset.py
  google/cloud/forseti/services/scanner/dao.py
Labels: cla: yes

#2824 updated travis website build to point to new repo
  .travis.yml
Labels: cla: yes

#2828 Close iterator for sqlalchemy query
  google/cloud/forseti/scanner/scanners/bucket_rules_scanner.py
Labels: cla: yes

#2831 Updated doc categories to show categories for latest.
  _data/doc_categories.yml
Labels: cla: yes

#2838 Suppressed inventory warning messages in inventory list command.
  google/cloud/forseti/services/inventory/service.py
Labels: cla: yes

#2836 Ignore 404 from get SA key api response.
  google/cloud/forseti/common/gcp_api/iam.py
  tests/common/gcp_api/iam_test.py
  tests/common/gcp_api/test_data/fake_iam_responses.py
Labels: cla: yes

#2841 Cherry pick #2838 to dev
  google/cloud/forseti/services/inventory/service.py
Labels: cla: yes

#2840 Cherry pick #2798 to dev
  google/cloud/forseti/common/gcp_api/iam.py
  tests/common/gcp_api/iam_test.py
  tests/common/gcp_api/test_data/fake_iam_responses.py
Labels: cla: yes

#2847 Update _config.yml to fix sitemap generation
  _config.yml
Labels: 3 - Working, cla: yes, module: website, priority: p1, triaged: yes

#2851 Downgraded pip to 9.0.3.
  deployment-templates/compute-engine/client/forseti-instance-client.py
  deployment-templates/compute-engine/server/forseti-instance-server.py
Labels: cla: yes

#2853 Updated ModelManager to make sure model builds properly
  google/cloud/forseti/services/dao.py
Labels: cla: yes

#2854 Removed old pip usage and updated to use python3 -m to locate pip3.
  deployment-templates/compute-engine/client/forseti-instance-client.py
  deployment-templates/compute-engine/server/forseti-instance-server.py
  install/gcp/gcp_installer.py
  install/gcp/installer/util/files.py
Labels: cla: yes

#2859 Fixed blacklist scanner to use decode the request content and updated model handle to use hex instead of str.
  google/cloud/forseti/scanner/audit/blacklist_rules_engine.py
  google/cloud/forseti/services/dao.py
  tests/scanner/scanners/blacklist_scanner_test.py
Labels: cla: yes

#2863 Removed uncessary call to site.main().
  install/gcp/gcp_installer.py
Labels: cla: yes

#2866 Decode content to string before attaching to an email.
  google/cloud/forseti/common/util/email/sendgrid_connector.py
Labels: cla: yes

#2869 Update jekyll_build.sh
  travis/jekyll_build.sh
Labels: cla: yes

#2870 Create 2019-05-29-forseti-day-presos.md
  _news/2019-05-29-forseti-day-presos.md
Labels: cla: yes

#2874 Update FAQ viewing and editing cron schedule
  _faq/installation_and_deployment/update-cron.md
Labels: cla: yes

#2876 Add in traceback if there is an error during scanner run
  google/cloud/forseti/scanner/scanner.py
Labels: cla: yes

#2875 Add in traceback if there is an error during notification
  google/cloud/forseti/notifier/notifier.py
  google/cloud/forseti/services/notifier/service.py
Labels: cla: yes

#2878 Skip logging error messages for delete pending projects during Inventory creation
  google/cloud/forseti/services/inventory/base/resources.py
Labels: cla: yes

#2879 Clarified in the config file to use project number / folder number / organization number when specifying the root resource id.
  configs/server/forseti_conf_server.yaml.in
Labels: cla: yes
